/*
    Author
    <table>
    date      author                    description
    --------  --------------            ----------
    20090326  toastops@                 Created
    </table>

    Description

*/

#include "ServiceMemory.h"
#include "ServiceNetwork.h"
#include "ServiceSystemTime.h"
#include "ByteArray.h"
#include "private/SipConfig.h"
#include "ISIPHeader.h"
#include "ISIPTransportErrorListener.h"
#include "ISIPTransportListener.h"
#include "SIPPrivate.h"
#include "SIPDebug.h"
#include "SIPConfigProxy.h"
#include "SIPFactoryProxy.h"
#include "SIPRTConfigUtils.h"
#include "SIPPortManager.h"
#include "SIPMessageBuffer.h"
#include "SIPSocket.h"
#include "SIPStreamSocket.h"
#include "SIPTransportHelper.h"
#include "SIPTransport.h"

__IMS_TRACE_TAG_SIP__;



PUBLIC
SIPTransport::SIPTransport(IN IMS_SINT32 nSlotId, IN IMS_SINT32 nType_)
    : ImsSlot(nSlotId)
    , nType(nType_)
    , bExplicitTargetProtocol(IMS_FALSE)
    , bIsRetransmission(IMS_FALSE)
    , bTxnFlowControlRequired(IMS_TRUE)
    , nNearEnd_PortC(SIP::PORT_UNSPECIFIED)
    , pSendBuffer(IMS_NULL)
    , nTransportExt(SIP::TRANSPORT_EXT_ANY)
    , nPortFlowControl(SIP::PORT_UNSPECIFIED)
    , pSocket(IMS_NULL)
    , piErrorListener(IMS_NULL)
{
}

PUBLIC VIRTUAL
SIPTransport::~SIPTransport()
{
    if (pSendBuffer != IMS_NULL)
    {
        delete pSendBuffer;
    }

    ReleaseSocket();

#ifdef __IMS_SIP_DEBUG__
    IMS_TRACE_D("Destructor :: SIPTransport", 0, 0, 0);
#endif
}

/*

Remarks

*/
PUBLIC
SIPSocket* SIPTransport::CreateTCPClientSocket()
{
    //---------------------------------------------------------------------------------------------

    if ((objTA_FarEnd.GetProtocol() != SIPTransportAddress::PROTOCOL_TCP)
            && (objTA_FarEnd.GetProtocol() != SIPTransportAddress::PROTOCOL_TLS))
    {
        IMS_TRACE_E(0, "Transport :: Protocol does not use TCP", 0, 0, 0);
        return IMS_NULL;
    }

    SIPSocket *pSocket = IMS_NULL;
    // RFC5626_FLOW_CONTROL
    IMS_SINT32 nTempPortC = nNearEnd_PortC;

    if (IsFlowControlPortConfigured())
    {
        IMS_TRACE_D("Transport :: Flow control (%d >> %d) will be applied",
                nTempPortC, nPortFlowControl, 0);

        nTempPortC = nPortFlowControl;
    }

    SIPTransportHelper *pTransportHelper = GetTransportHelper();

    SIPSocketAddress objSA;
    objSA.SetIPAddress(objTA_NearEnd.GetIPAddress());
    objSA.SetPort(nTempPortC);

    if ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
            || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS))
    {
        SIPSocketAddress objSA_FarEnd;

        objSA.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        objSA_FarEnd.SetIPAddress(objTA_FarEnd.GetIPAddress());
        objSA_FarEnd.SetPort(objTA_FarEnd.GetPort());
        objSA_FarEnd.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        // First, check the accepted TCP connection to re-use the TCP connection
        pSocket = pTransportHelper->OpenStreamSocket(objSA, objSA_FarEnd);

        objSA.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT);
        objSA_FarEnd.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT);

        if (pSocket == IMS_NULL)
        {
            pSocket = pTransportHelper->OpenStreamSocket(objSA, objSA_FarEnd);
        }

        if ((pSocket == IMS_NULL)
                && IsFlowControlPortConfigured()
                && IsTransactionFlowControlRequired())
        {
            IMS_TRACE_D("Transport :: TCP client (%s, %d) can't be created by flow control",
                    SIPDebug::GetIP(objSA.GetIPAddress()), objSA.GetPort(), 0);
            return IMS_NULL;
        }

        // For port range configuration
        IMS_SINT32 nTCPPortC = 0;

        if (pSocket == IMS_NULL)
        {
            // TCP client socket
            //  1) The address will be used as the listening point's one.
            //  2) The port number will be generated by the socket library of the system.
            if (!IsIPSecRequired()
                    && !IsFlowControlPortConfigured()
                    && !IsTCPConnectionOnlyRequired())
            {
                if (SIPRTConfigUtils::IsTcpPortRangeConfigured(GetSlotId()))
                {
                    SIPPortManager *pPortMngr = SIPPortManager::GetInstance();

                    if (pPortMngr->IsPortCProvisioned())
                    {
                        pSocket = pTransportHelper->OpenStreamSocket(objSA, objSA_FarEnd);

                        if (pSocket == IMS_NULL)
                        {
                            nTCPPortC = pPortMngr->GetPortC(objSA.GetIPAddress());
                        }
                    }
                }

                objSA.SetPort(nTCPPortC);
            }
        }

        if (pSocket == IMS_NULL)
        {
            if (nTCPPortC > 0)
            {
                // Use the port number selected by the previous condition logic.
            }
            else if (nTempPortC != objTA_NearEnd.GetPort())
            {
                objSA.SetPort(nTempPortC);
            }
            else
            {
                if (IsTCPConnectionOnlyRequired())
                {
                    IMS_TRACE_D("Transport :: TCP client connection is only required...", 0, 0, 0);
                    objSA.SetPort(nTempPortC);
                }
                else if (IsFlowControlPortConfigured())
                {
                    IMS_TRACE_D("Transport :: Flow control is required", 0, 0, 0);
                    objSA.SetPort(nTempPortC);
                }
            }

            // If the transport protocol is TLS, SSL socket will be created...
            if (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS)
            {
                objSA.SetSecure(IMS_TRUE);
            }

            pSocket = pTransportHelper->CreateStreamSocket(objSA, objSA_FarEnd);

            if (pSocket == IMS_NULL)
            {
                // LOG_EXCLUDING_SERVER_INFO
                IMS_TRACE_E(0, "Creating TCP client (FAR - %s, %d)",
                        SIPRTConfigUtils::IsRoutingInfoHiddenInLog(GetSlotId()) ? \
                        "xxx" : SIPDebug::GetIP(objSA_FarEnd.GetIPAddress()),
                        objSA_FarEnd.GetPort(), 0);
                return IMS_NULL;
            }

            IMS_TRACE_D("Transport :: TCP client (%s, %d) is created",
                    SIPDebug::GetIP(objSA.GetIPAddress()), objSA.GetPort(), 0);
        }
        else
        {
            IMS_TRACE_D("Transport :: TCP client (%s, %d) is created",
                    SIPDebug::GetIP(objSA.GetIPAddress()), nTempPortC, 0);
        }
    }

    return pSocket;
}

/*

Remarks

*/
PUBLIC
IMS_BOOL SIPTransport::EncodeMessage(IN_OUT SipMessage *&pstMessage, OUT ByteArray &objBuffer)
{
    RCPtr<SIPMessageBuffer> pMessageBuffer = SIPMessageBuffer::GetInstance();
    IMS_SINT32 nBuffLen = pMessageBuffer->GetLength();
    IMS_BYTE *pBuffer = pMessageBuffer->GetBuffer(GetSlotId());

    //---------------------------------------------------------------------------------------------

    IMS_MEM_Memset(pBuffer, 0x00, nBuffLen);

    if (!SIPStack::EncodeMessage(pstMessage, SIPPrivate::GetEncodingOptions(), pBuffer, nBuffLen))
        return IMS_FALSE;

    objBuffer.Append(pBuffer, nBuffLen);

    return IMS_TRUE;
}

/*

Remarks

*/
PUBLIC
const SIPTransportAddress& SIPTransport::GetAddress(IN IMS_SINT32 nTA /* = TA_NEAR */) const
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        return objTA_NearEnd;
    else
        return objTA_FarEnd;
}

/*

Remarks

*/
PUBLIC
IMS_SINT32 SIPTransport::GetPortC() const
{
    //---------------------------------------------------------------------------------------------

    return nNearEnd_PortC;
}

/*

Remarks
 RFC5626_FLOW_CONTROL
*/
PUBLIC
IMS_SINT32 SIPTransport::GetPortFlowControl() const
{
    //---------------------------------------------------------------------------------------------

    return nPortFlowControl;
}

/*

Remarks

*/
PUBLIC
const IPAddress& SIPTransport::GetIPAddress(IN IMS_SINT32 nTA /* = TA_NEAR */)
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
    {
        return objTA_NearEnd.GetIPAddress();
    }
    else
    {
        return objTA_FarEnd.GetIPAddress();
    }
}

/*

Remarks

*/
PUBLIC
IMS_SINT32 SIPTransport::GetPort(IN IMS_SINT32 nTA /* = TA_NEAR */) const
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        return objTA_NearEnd.GetPort();
    else
        return objTA_FarEnd.GetPort();
}

/*

Remarks

*/
PUBLIC
IMS_SINT32 SIPTransport::GetProtocol(IN IMS_SINT32 nTA /* = TA_NEAR */) const
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        return objTA_NearEnd.GetProtocol();
    else
        return objTA_FarEnd.GetProtocol();
}

/*

Remarks
 MULTI_REG_TRANSPORT
*/
PUBLIC
IMS_SINT32 SIPTransport::GetTransportExt() const
{
    //---------------------------------------------------------------------------------------------

    return nTransportExt;
}

/*

Remarks

*/
PUBLIC
void SIPTransport::InitRetransmissionFlag()
{
    //---------------------------------------------------------------------------------------------

    bIsRetransmission = IMS_FALSE;
}

/*

Remarks
 MULTI_REG_SIP_PROFILE
*/
PUBLIC
IMS_BOOL SIPTransport::InitTransportDetails(IN CONST SIPTransport *pTransport,
        IN CONST SIPProfile *pSIPProfile/* = IMS_NULL */)
{
    //---------------------------------------------------------------------------------------------

    if (pTransport == IMS_NULL)
    {
        return IMS_FALSE;
    }

    bExplicitTargetProtocol = pTransport->bExplicitTargetProtocol;
    bTxnFlowControlRequired = pTransport->bTxnFlowControlRequired;
    nNearEnd_PortC = pTransport->nNearEnd_PortC;
    objTA_NearEnd = pTransport->objTA_NearEnd;
    objTA_FarEnd = pTransport->objTA_FarEnd;

    // MULTI_REG_TRANSPORT
    nTransportExt = pTransport->nTransportExt;
    // RFC5626_FLOW_CONTROL
    nPortFlowControl = pTransport->nPortFlowControl;

    if (!ReserveResource(pSIPProfile))
    {
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

/*

Remarks

*/
PUBLIC
IMS_BOOL SIPTransport::InitTransportOnMessageReceived(IN SipMessage * /* pstMessage */)
{
    //---------------------------------------------------------------------------------------------

    if (nType == TYPE_CLIENT)
    {
        InitRetransmissionFlag();
    }

    return IMS_TRUE;
}

/*

Remarks

*/
PUBLIC
IMS_BOOL SIPTransport::IsIPSecRequired() const
{
    //---------------------------------------------------------------------------------------------

    return (((nTransportExt & SIP::TRANSPORT_EXT_IPSEC) != 0)
            || ((nTransportExt & SIP::TRANSPORT_EXT_IPSEC_UDP_ENC) != 0));
}

/*

Remarks
 MULTI_REG_TRANSPORT
*/
PUBLIC
IMS_BOOL SIPTransport::IsTCPConnectionOnlyRequired() const
{
    //---------------------------------------------------------------------------------------------

    return ((nTransportExt & SIP::TRANSPORT_EXT_TCP_ONLY) != 0);
}

/*

Remarks

*/
PUBLIC
IMS_BOOL SIPTransport::IsTransactionFlowControlRequired() const
{
    //---------------------------------------------------------------------------------------------

    return bTxnFlowControlRequired;
}

/*

Remarks

*/
PUBLIC
IMS_BOOL SIPTransport::SendToNetwork(IN CONST IMS_BYTE *pBuffer, IN IMS_SINT32 nBuffLen,
        IN IMS_BOOL bNotifyError /* = IMS_TRUE */)
{
    //---------------------------------------------------------------------------------------------

    // Find a socket to send an SIP message
    if (pSocket == IMS_NULL)
    {
        pSocket = LookupSocket();

        if (pSocket == IMS_NULL)
        {
            IMS_TRACE_E(0, "Can't find a proper SIP socket information from the transport layer.",
                    0, 0, 0);
            goto EXIT_SendToNetwork;
        }
    }

    // For an initial TCP client connection...
    if (!pSocket->Connect())
    {
        IMS_TRACE_E(0, "Connecting transport channel failed ...", 0, 0, 0);
        goto EXIT_SendToNetwork;
    }

    if (pSocket->GetState() != SIPSocket::STATE_CONNECTED)
    {
        IMS_TRACE_D("___ Waiting the establishment of transport channel ...", 0, 0, 0);

        if (pSendBuffer != IMS_NULL)
            delete pSendBuffer;

        pSendBuffer = new ByteArray(pBuffer, nBuffLen);

        return IMS_TRUE;
    }

    if (!TransmitMessage(pBuffer, nBuffLen))
    {
        IMS_TRACE_E(0, "Transmitting SIP message to the destination (%s:%d) failed",
                SIPDebug::GetIP(objTA_FarEnd.GetIPAddress()), objTA_FarEnd.GetPort(), 0);
        goto EXIT_SendToNetwork;
    }

    if (!bIsRetransmission)
    {
        bIsRetransmission = IMS_TRUE;
    }

    return IMS_TRUE;

EXIT_SendToNetwork:
    if (bNotifyError && bIsRetransmission && (piErrorListener != IMS_NULL))
    {
        AString strError;

        strError.Sprintf("%d Message retransmission failed", SIPError::TRANSPORT_E_CODE_107);
        piErrorListener->TransportError_NotifyError(SIPSocket::ERROR_SEND_FAILED, strError);
    }

    return IMS_FALSE;
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetAddress(IN CONST SIPTransportAddress &objTA,
        IN IMS_SINT32 nTA /* = TA_NEAR */)
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        objTA_NearEnd = objTA;
    else
        objTA_FarEnd = objTA;
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetExplicitTargetProtocol(IN IMS_BOOL bExplicitTargetProtocol)
{
    //---------------------------------------------------------------------------------------------

    this->bExplicitTargetProtocol = bExplicitTargetProtocol;
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetIPAddress(IN CONST IPAddress &objIPAddress,
        IN IMS_SINT32 nTA /* = TA_NEAR */)
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        objTA_NearEnd.SetIPAddress(objIPAddress);
    else
        objTA_FarEnd.SetIPAddress(objIPAddress);
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetListener(IN ISIPTransportErrorListener *piListener)
{
    //---------------------------------------------------------------------------------------------

    piErrorListener = piListener;
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetPort(IN IMS_SINT32 nPort, IN IMS_SINT32 nTA /* = TA_NEAR */)
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        objTA_NearEnd.SetPort(nPort);
    else
        objTA_FarEnd.SetPort(nPort);
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetProtocol(IN IMS_SINT32 nProtocol, IN IMS_SINT32 nTA /* = TA_NEAR */)
{
    //---------------------------------------------------------------------------------------------

    if (nTA == TA_NEAR)
        objTA_NearEnd.SetProtocol(nProtocol);
    else
        objTA_FarEnd.SetProtocol(nProtocol);
}

/*

Remarks

*/
PUBLIC
void SIPTransport::SetTransactionFlowControlRequired(IN IMS_BOOL bFlowControlRequired)
{
    //---------------------------------------------------------------------------------------------

    bTxnFlowControlRequired = bFlowControlRequired;
}

/*

Remarks
 RFC5626_FLOW_CONTROL, MULTI_REG_TRANSPORT
*/
PUBLIC
void SIPTransport::SetTransportTuple(IN CONST IPAddress &objIPA,
        IN IMS_SINT32 nPortS, IN IMS_SINT32 nPortC,
        IN IMS_SINT32 nPortFC /* = SIP::PORT_UNSPECIFIED */,
        IN IMS_SINT32 nTransportExt /* = 0 (ANY) */)
{
    //---------------------------------------------------------------------------------------------

    objTA_NearEnd.SetIPAddress(objIPA);
    objTA_NearEnd.SetPort(nPortS);

    nNearEnd_PortC = nPortC;

    // RFC5626_FLOW_CONTROL
    nPortFlowControl = nPortFC;

    // MULTI_REG_TRANSPORT
    this->nTransportExt = nTransportExt;

    IMS_TRACE_D("SetTransportTuple: port-c=%d, port-fc=%d, transportExt=%08X",
            nPortC, nPortFC, nTransportExt);
}

/*

Remarks

*/
PUBLIC
void SIPTransport::StoreResource()
{
    //---------------------------------------------------------------------------------------------

    // Store the socket if and only if the transport protocol is TCP
    if ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
            || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS))
    {
        SIPSocketAddress objSA;
        SIPSocketAddress objSA_FarEnd;

        objSA.SetIPAddress(objTA_NearEnd.GetIPAddress());
        objSA.SetPort(objTA_NearEnd.GetPort());
        objSA.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        objSA_FarEnd.SetIPAddress(objTA_FarEnd.GetIPAddress());
        objSA_FarEnd.SetPort(objTA_FarEnd.GetPort());
        objSA_FarEnd.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        // First, check the accepted TCP connection to re-use the TCP connection
        pSocket = GetTransportHelper()->OpenStreamSocket(objSA, objSA_FarEnd);

        if (pSocket != IMS_NULL)
        {
            pSocket->SetListener(this);

            IMS_TRACE_D("Transport :: TCP connection is bound", 0, 0, 0);
        }
    }
}

/*

Remarks
 MULTI_REG_SIP_PROFILE
*/
PUBLIC VIRTUAL
IMS_BOOL SIPTransport::FormViaHeader(IN_OUT SipMessage *& /* pstMessage */,
        IN CONST SIPProfile */*pSIPProfile = IMS_NULL*/)
{
    //---------------------------------------------------------------------------------------------

    return IMS_TRUE;
}

/*

Remarks
 MULTI_REG_SIP_PROFILE
*/
PUBLIC VIRTUAL
IMS_BOOL SIPTransport::ReserveResource(IN CONST SIPProfile *pSIPProfile/* = IMS_NULL*/)
{
    //---------------------------------------------------------------------------------------------

    if (!IsNetworkConnectionAvailable())
        return IMS_FALSE;

    // Check the validity of transport information (Type of transport & port number)

    // Reserve the socket resource
    if (!ReserveSocket(pSIPProfile))
    {
        ReleaseSocket();
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

/*

Remarks

*/
PUBLIC VIRTUAL
IMS_BOOL SIPTransport::UpdateDestinationInfo(IN SipMessage * /* pstMessage */,
        IN IMS_BOOL /* bRoutingLR = IMS_TRUE */,
        IN SipAddrSpec * /* pstImplicitRoute = IMS_NULL */)
{
    //---------------------------------------------------------------------------------------------

    return IMS_TRUE;
}

/*

Remarks

*/
PUBLIC VIRTUAL
IMS_SINT32 SIPTransport::ValidateViaHeader(IN SipMessage * /* pstMessage */)
{
    //---------------------------------------------------------------------------------------------

    return SIPPrivate::MESSAGE_VALID;
}

/*

Remarks

*/
PUBLIC GLOBAL
AString SIPTransport::CreateSocketErrorMessage(IN IMS_SINT32 nErrorCode,
        IN IMS_SINT32 nSocketType/* = SIPSocketAddress::SOCKET_NONE*/)
{
    AString strError(AString::ConstNull());

    //---------------------------------------------------------------------------------------------

    switch (nErrorCode)
    {
    case SIPSocket::ERROR_CLOSED:
        // SIP_TRANSPORT_ERROR_REPORT_ON_TXN
        if (nSocketType == SIPSocketAddress::SOCKET_TCP_CLIENT)
        {
            strError.Sprintf("%d Socket is closed by peer", SIPError::TRANSPORT_E_CODE_104);
        }
        break;

    case SIPSocket::ERROR_CONNECT_FAILED:
        strError.Sprintf("%d Socket connect failed", SIPError::TRANSPORT_E_CODE_105);
        break;

    case SIPSocket::ERROR_DATA_CONNECTION_LOST:
        strError.Sprintf("%d Socket is abnormally closed", SIPError::TRANSPORT_E_CODE_106);
        break;

    case SIPSocket::ERROR_WOULDBLOCK_TIMEDOUT:
        strError.Sprintf("%d Too long wouldblock", SIPError::TRANSPORT_E_CODE_101);
        break;

    case SIPSocket::ERROR_CONNECTION_TIMEDOUT:
        strError.Sprintf("%d TCP connection timed out", SIPError::TRANSPORT_E_CODE_102);
        break;

    default:
        break;
    }

    return strError;
}

/*

Remarks

*/
PUBLIC GLOBAL
IMS_BOOL SIPTransport::GetHostNPortFromViaHeader(IN SipMessage *pstMessage,
        OUT AString &strHost, OUT IMS_SINT32 &nPort)
{
    //---------------------------------------------------------------------------------------------

    return SIPStack::GetHostNPortFromViaHeader(pstMessage, strHost, nPort);
}

/*

Remarks

*/
PUBLIC GLOBAL
void SIPTransport::ParseHostNPort(IN CONST AString &strHostNPort, OUT AString &strHost,
        OUT IMS_SINT32 &nPort)
{
    //---------------------------------------------------------------------------------------------

    SIPStack::ParseHostNPort(strHostNPort, strHost, nPort);
}

/*

Remarks

*/
PUBLIC GLOBAL
void SIPTransport::PrintMessage(IN IMS_SINT32 nSlotId, IN IMS_BOOL bSEND,
        IN CONST SIPTransportAddress &objTA_FarEnd,
        IN CONST IMS_CHAR *pszMessage, IN IMS_SINT32 nLength)
{
    // SEND or RECV:Message Length:Transport Type:IP address:Port
    // For example,
    //    SEND:    <<<==SEND:512:UDP:10.168.114.153:5060==
    //    RECV:    ==RECV:512:TCP:10.168.114.153:5060==>>>

    const IMS_CHAR LOG_SEND[] = "<<<==SEND:%d:%s:%s:%d_s%d==";
    const IMS_CHAR LOG_RECV[] = "==RECV:%d:%s:%s:%d_s%d==>>>";

    const IMS_CHAR *pszFORMAT;
    const IMS_CHAR *pszTRANSPORT;
    AString strLOG;

    //-----------------------------------------------------------------------------------------

    // Summary of message -- starts

    if (bSEND)
    {
        pszFORMAT = LOG_SEND;
    }
    else
    {
        pszFORMAT = LOG_RECV;
    }

    if (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_UDP)
    {
        pszTRANSPORT = SIP::STR_UDP_CAPS;
    }
    else if (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
    {
        pszTRANSPORT = SIP::STR_TCP_CAPS;
    }
    else if (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS)
    {
        pszTRANSPORT = SIP::STR_TLS_CAPS;
    }
    else
    {
        pszTRANSPORT = "UNKNOWN";
    }

    // LOG_EXCLUDING_SERVER_INFO
    if (SIPRTConfigUtils::IsMessageHiddenInLog(nSlotId))
    {
        strLOG.Sprintf(pszFORMAT, nLength, pszTRANSPORT,
                objTA_FarEnd.GetIPAddress().IsIPv6Address() ? "::" : "0.0.0.0",
                objTA_FarEnd.GetPort(), nSlotId);
    }
    else
    {
        strLOG.Sprintf(pszFORMAT, nLength, pszTRANSPORT,
                SIPDebug::GetIP(objTA_FarEnd.GetIPAddress()), objTA_FarEnd.GetPort(), nSlotId);
    }

    // Summary of message -- ends

    // Display whole SIP message
    // LOG_EXCLUDING_SERVER_INFO
    if (SIPRTConfigUtils::IsMessageHiddenInLog(nSlotId))
    {
        IMS_TRACE_SIP(strLOG.GetStr(), pszMessage, (nLength < 11) ? nLength : 11, IMS_FALSE);
    }
    else
    {
        IMS_TRACE_SIP(strLOG.GetStr(), pszMessage, nLength, IMS_FALSE);
    }
}

/*

Remarks

*/
PROTECTED VIRTUAL
void SIPTransport::Socket_NotifyError(IN SIPSocket *pSocket, IN IMS_SINT32 nErrorCode)
{
    //---------------------------------------------------------------------------------------------

    if (this->pSocket != pSocket)
    {
        IMS_TRACE_D("Socket_NotifyError() :: Socket not matched", 0, 0, 0);
        return;
    }

    NotifyTransportError(nErrorCode);

    if (pSendBuffer != IMS_NULL)
    {
        delete pSendBuffer;
        pSendBuffer = IMS_NULL;
    }

    ReleaseSocket();
}

/*

Remarks

*/
PROTECTED VIRTUAL
void SIPTransport::Socket_SendEnabled(IN SIPSocket *pSocket)
{
    //---------------------------------------------------------------------------------------------

    (void) pSocket;

    if (this->pSocket == IMS_NULL)
    {
        // Do nothing...
        IMS_TRACE_D("Socket NULL", 0, 0, 0);
        return;
    }

    if (this->pSocket != pSocket)
    {
        // Do nothing...
        IMS_TRACE_D("Socket not matched", 0, 0, 0);
        return;
    }

    if (this->pSocket->GetState() != SIPSocket::STATE_CONNECTED)
    {
        // Do nothing ...
        IMS_TRACE_D("Socket is not ready", 0, 0, 0);
        return;
    }

    // In case of UDP transport, if the socket is created at the first, the below operation needs.
    if (pSendBuffer != IMS_NULL)
    {
        if (!TransmitMessage(pSendBuffer->GetData(), pSendBuffer->GetLength()))
        {
            if (piErrorListener != IMS_NULL)
            {
                AString strError;

                strError.Sprintf("%d Message transmission failed", SIPError::TRANSPORT_E_CODE_103);
                piErrorListener->TransportError_NotifyError(SIPSocket::ERROR_SEND_FAILED, strError);
            }
        }
        else
        {
            // If this message(first message) is successfully sent,
            // then the retransmission flag will be set in here.
            if (!bIsRetransmission)
            {
                bIsRetransmission = IMS_TRUE;
            }
        }
    }
}

/*

Remarks

*/
PROTECTED
void SIPTransport::CorrectNearEndAddress()
{
    //---------------------------------------------------------------------------------------------

    // Correct the port number with a default port if it does not explicitly
    if (objTA_NearEnd.GetPort() == SIP::PORT_UNSPECIFIED)
    {
        if (objTA_NearEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS)
        {
            objTA_NearEnd.SetPort(SIP::PORT_5061);
        }
        else
        {
            objTA_NearEnd.SetPort(SIP::PORT_5060);
        }
    }

    // Set the local IP address
#if 0
    if (objTA_NearEnd.GetIPAddress().Equals(IPAddress::NONE))
    {
        objTA_NearEnd.SetIPAddress(piNetConnection->GetLocalAddress());
    }
#endif
}

/*

Remarks

*/
PROTECTED
SIPTransportHelper* SIPTransport::GetTransportHelper() const
{
    return SIPFactoryProxy::GetInstance()->GetTransportHelper(GetSlotId());
}

/*

Remarks

*/
PROTECTED
IMS_BOOL SIPTransport::IsExplicitTargetProtocolSelected() const
{
    //---------------------------------------------------------------------------------------------

    return bExplicitTargetProtocol;
}

/*

Remarks
 RFC5626_FLOW_CONTROL
*/
PROTECTED
IMS_BOOL SIPTransport::IsFlowControlPortConfigured() const
{
    //---------------------------------------------------------------------------------------------

    // FIXME: consider more cases
    return SIP::IsPortSpecified(nPortFlowControl);
}

/*

Remarks

*/
PROTECTED
IMS_BOOL SIPTransport::IsIPSecUDPEncRequired() const
{
    //---------------------------------------------------------------------------------------------

    return ((nTransportExt & SIP::TRANSPORT_EXT_IPSEC_UDP_ENC) != 0);
}


/*

Remarks
 MULTI_REG_TRANSPORT
*/
PROTECTED
IMS_BOOL SIPTransport::IsTargetProtocolConfigured() const
{
    //---------------------------------------------------------------------------------------------

    return (((nTransportExt & SIP::TRANSPORT_EXT_UDP) != 0)
            || ((nTransportExt & SIP::TRANSPORT_EXT_TCP) != 0)
            || ((nTransportExt & SIP::TRANSPORT_EXT_TLS) != 0));
}

/*

Remarks

*/
PROTECTED
void SIPTransport::NotifyTransportError(IN IMS_SINT32 nErrorCode)
{
    //---------------------------------------------------------------------------------------------

    if (piErrorListener == IMS_NULL)
    {
        IMS_TRACE_D("Transport :: No Listener, Error (%d)", nErrorCode, 0, 0);
        return;
    }

    IMS_TRACE_D("Transport :: Error (%d)", nErrorCode, 0, 0);

    switch (nErrorCode)
    {
    case SIPSocket::ERROR_CLOSED:
    case SIPSocket::ERROR_CONNECT_FAILED:
    case SIPSocket::ERROR_DATA_CONNECTION_LOST:
        if (pSocket == IMS_NULL)
        {
            // no-op
            return;
        }
        break;
    default:
        break;
    }

    IMS_SINT32 nSocketType = SIPSocketAddress::SOCKET_NONE;

    if (nErrorCode == SIPSocket::ERROR_CLOSED)
    {
        nSocketType = pSocket->GetType();
    }

    AString strError = CreateSocketErrorMessage(nErrorCode, nSocketType);

    if (strError.GetLength() > 0)
    {
        piErrorListener->TransportError_NotifyError(SIPError::TRANSPORT_ERROR, strError);
    }
}

/*

Remarks

*/
PRIVATE
IMS_BOOL SIPTransport::IsNetworkConnectionAvailable() const
{
    //---------------------------------------------------------------------------------------------

    if (NetworkService::GetNetworkService()->FindConnection(
            objTA_NearEnd.GetIPAddress()) == IMS_NULL)
    {
        IMS_TRACE_E(0, "Network (%s) is not available",
                SIPDebug::GetIP(objTA_NearEnd.GetIPAddress()), 0, 0);
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

/*

Remarks

*/
PRIVATE
SIPSocket* SIPTransport::LookupSocket() const
{
    SIPTransportHelper *pTransportHelper = GetTransportHelper();
    SIPSocketAddress objSA;

    //---------------------------------------------------------------------------------------------

    if ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
            || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS))
    {
        SIPSocketAddress objSA_FarEnd;

        objSA.SetIPAddress(objTA_NearEnd.GetIPAddress());
        objSA.SetPort(nNearEnd_PortC);
        objSA.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT);

        objSA_FarEnd.SetIPAddress(objTA_FarEnd.GetIPAddress());
        objSA_FarEnd.SetPort(objTA_FarEnd.GetPort());
        objSA_FarEnd.SetType(SIPSocketAddress::SOCKET_TCP_CLIENT);

        return pTransportHelper->OpenStreamSocket(objSA, objSA_FarEnd);
    }
    else
    {
        objSA.SetIPAddress(objTA_NearEnd.GetIPAddress());
        objSA.SetPort(nNearEnd_PortC);
        objSA.SetType(SIPSocketAddress::SOCKET_UDP);

        return pTransportHelper->Open(objSA);
    }
}

/*

Remarks

*/
PRIVATE
void SIPTransport::ReleaseSocket()
{
    //---------------------------------------------------------------------------------------------

    if (pSocket != IMS_NULL)
    {
        GetTransportHelper()->Destroy(pSocket, this);
        pSocket = IMS_NULL;
    }
}

/*

Remarks

*/
PRIVATE
IMS_BOOL SIPTransport::ReserveSocket(IN CONST SIPProfile *pSIPProfile/* = IMS_NULL*/)
{
    // RFC5626_FLOW_CONTROL
    IMS_SINT32 nTempPortC = nNearEnd_PortC;

    //---------------------------------------------------------------------------------------------

    if (IsFlowControlPortConfigured())
    {
        IMS_TRACE_D("Transport :: Flow control (%d >> %d) will be applied",
                nTempPortC, nPortFlowControl, 0);

        nTempPortC = nPortFlowControl;
    }

    // If the transport has already the connected socket, do not reserve the socket again.
    if (pSocket != IMS_NULL)
    {
        // Check if the port is same or not...
        if (nType != TYPE_CLIENT)
        {
            // In case of server transport & TCP protocol used
            IMS_TRACE_D("Transport :: server transport will use an existing TCP connection",
                    0, 0, 0);
            return IMS_TRUE;
        }

        IPAddress objIPA;
        IMS_UINT32 nPort = 0;
        IMS_BOOL bCheckTCPSocketReusability = IMS_FALSE;

        pSocket->GetSockName(objIPA, nPort);

        if (nTempPortC == static_cast<IMS_SINT32>(nPort))
        {
            if ((pSocket->GetType() == SIPSocketAddress::SOCKET_UDP)
                    && (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_UDP))
            {
                // If the port is same, the socket will be re-used...
                IMS_TRACE_D("Transport :: UDP client (%s, %d) is re-used",
                        SIPDebug::GetIP(objIPA), nPort, 0);
                return IMS_TRUE;
            }
            else if ((pSocket->GetType() == SIPSocketAddress::SOCKET_TCP_CLIENT)
                    && ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
                        || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS)))
            {
                bCheckTCPSocketReusability = IMS_TRUE;
            }
        }
        // Case: random port number for TCP connection
        else if ((nTempPortC == 0) || (nTempPortC == objTA_NearEnd.GetPort()))
        {
            if ((pSocket->GetType() == SIPSocketAddress::SOCKET_TCP_CLIENT)
                    && ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
                        || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS)))
            {
                bCheckTCPSocketReusability = IMS_TRUE;
            }
        }

        if (bCheckTCPSocketReusability)
        {
            IPAddress objPeerIPA;
            IMS_UINT32 nPeerPort = 0;

            pSocket->GetPeerName(objPeerIPA, nPeerPort);

            if (objPeerIPA.Equals(objTA_FarEnd.GetIPAddress())
                    && (objTA_FarEnd.GetPort() == static_cast<IMS_SINT32>(nPeerPort)))
            {
                // If the port is same, the socket will be re-used...
                IMS_TRACE_D("Transport :: TCP client (%s, %d) is re-used",
                        SIPDebug::GetIP(objIPA), nPort, 0);

                // MULTI_REG_SIP_PROFILE
                SIPStreamSocket *pStreamSocket = DYNAMIC_CAST(SIPStreamSocket*, pSocket);

                pStreamSocket->SetConfigForSIPKeepAlive(
                        SIPConfigProxy::IsKeepAliveConfigured(GetSlotId(), pSIPProfile));
                return IMS_TRUE;
            }
            else
            {
                IMS_TRACE_D("Transport :: TCP client (%s, %d) is matched",
                        SIPDebug::GetIP(objIPA), nPort, 0);
                // LOG_EXCLUDING_SERVER_INFO
                IMS_TRACE_D("Transport :: TCP client (peer) (%s, %d) is not matched",
                        SIPRTConfigUtils::IsRoutingInfoHiddenInLog(GetSlotId()) ? \
                        "xxx" : SIPDebug::GetIP(objPeerIPA),
                        nPeerPort, 0);
            }
        }

        // Release the previous socket and create a new socket...
        ReleaseSocket();
    }

    if ((objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TCP)
            || (objTA_FarEnd.GetProtocol() == SIPTransportAddress::PROTOCOL_TLS))
    {
        pSocket = CreateTCPClientSocket();

        if (pSocket == IMS_NULL)
        {
            return IMS_FALSE;
        }

        SIPStreamSocket *pStreamSocket = DYNAMIC_CAST(SIPStreamSocket*, pSocket);

        // RFC5626_FLOW_CONTROL
        if (IsFlowControlPortConfigured())
        {
            if (!pStreamSocket->IsKeepAlivePermanent())
            {
                pStreamSocket->SetKeepAlivePolicy(SipConfig::TcpTimerValues::PERMANENT);
            }
        }

        // MULTI_REG_SIP_PROFILE
        pStreamSocket->SetConfigForSIPKeepAlive(
                SIPConfigProxy::IsKeepAliveConfigured(GetSlotId(), pSIPProfile));
    }
    else
    {
        SIPSocketAddress objSA;
        objSA.SetIPAddress(objTA_NearEnd.GetIPAddress());
        objSA.SetPort(nTempPortC);

        // Open the UDP client socket
        objSA.SetType(SIPSocketAddress::SOCKET_UDP);

        pSocket = GetTransportHelper()->Create(objSA);

        if (pSocket == IMS_NULL)
        {
            IMS_TRACE_E(0, "Creating UDP client (%s, %d)",
                    SIPDebug::GetIP(objSA.GetIPAddress()), objSA.GetPort(), 0);
            return IMS_FALSE;
        }

        IMS_TRACE_D("Transport :: UDP client (%s, %d) is created",
                SIPDebug::GetIP(objSA.GetIPAddress()), objSA.GetPort(), 0);
    }

    pSocket->SetListener(this);

    return IMS_TRUE;
}

/*

Remarks

*/
PRIVATE
IMS_BOOL SIPTransport::TransmitMessage(IN CONST IMS_BYTE *pBuffer, IN IMS_SINT32 nBuffLen)
{
    //---------------------------------------------------------------------------------------------

    // If SIP TX packet is blocked by the application,
    // don't send the packet via Socket.
    if (SIPRTConfigUtils::IsFeatureSipTxPacketBlockedEnabled(GetSlotId()))
    {
        PrintMessage(GetSlotId(), IMS_TRUE, objTA_FarEnd, (const IMS_CHAR*) pBuffer, nBuffLen);
        return IMS_TRUE;
    }

    IMS_SINT32 nSentBytes = pSocket->Send(pBuffer, nBuffLen,
                                objTA_FarEnd.GetPort(), objTA_FarEnd.GetIPAddress());

    // DEBUGGING message ...
    {
        PrintMessage(GetSlotId(), IMS_TRUE, objTA_FarEnd, (const IMS_CHAR*) pBuffer, nBuffLen);
    }

    if (nSentBytes == ISocket::RESULT_ERROR)
    {
        if (pSendBuffer != IMS_NULL)
        {
            delete pSendBuffer;
            pSendBuffer = IMS_NULL;
        }

        IMS_TRACE_E(0, "Sending SIP message to the network failed", 0, 0, 0);
        return IMS_FALSE;
    }
    else if (nSentBytes < nBuffLen)
    {
        ByteArray objBuffer;

        objBuffer.Append(&pBuffer[nSentBytes], nBuffLen - nSentBytes);

        if (pSendBuffer != IMS_NULL)
            delete pSendBuffer;

        pSendBuffer = new ByteArray(objBuffer);
    }
    else
    {
        if (pSendBuffer != IMS_NULL)
        {
            delete pSendBuffer;
            pSendBuffer = IMS_NULL;
        }
    }

    IMS_TRACE_I("___ SIPTransport - SENT BYTES (%d) ___", nSentBytes, 0, 0);

    return IMS_TRUE;
}
