/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "ByteArray.h"
#include "ServiceMemory.h"
#include "ServiceNetwork.h"
#include "ServiceSystemTime.h"

#include "private/SipConfig.h"

#include "ISipHeader.h"
#include "ISipTransportListener.h"
#include "SipConfigProxy.h"
#include "SipDebug.h"
#include "SipFactoryProxy.h"
#include "SipMessageBuffer.h"
#include "SipPortManager.h"
#include "SipRtConfigUtils.h"
#include "SipStack.h"
#include "SipStreamSocket.h"
#include "SipTransport.h"
#include "SipTransportHelper.h"

__IMS_TRACE_TAG_SIP_CORE__;

PUBLIC
SipTransport::SipTransport(IN IMS_SINT32 nSlotId, IN IMS_SINT32 nType) :
        ImsSlot(nSlotId),
        m_nType(nType),
        m_bExplicitTargetProtocol(IMS_FALSE),
        m_bIsRetransmission(IMS_FALSE),
        m_bTxnFlowControlRequired(IMS_TRUE),
        m_nNearEndPortC(Sip::PORT_UNSPECIFIED),
        m_pSendBuffer(IMS_NULL),
        m_nTransportExt(Sip::TRANSPORT_EXT_ANY),
        m_nPortFlowControl(Sip::PORT_UNSPECIFIED),
        m_pSocket(IMS_NULL),
        m_piListener(IMS_NULL)
{
}

PUBLIC VIRTUAL SipTransport::~SipTransport()
{
    if (m_pSendBuffer != IMS_NULL)
    {
        delete m_pSendBuffer;
    }

    ReleaseSocket();

#ifdef __IMS_SIP_DEBUG__
    IMS_TRACE_D("Destructor :: SipTransport", 0, 0, 0);
#endif
}

PUBLIC
SipSocket* SipTransport::CreateTcpClientSocket()
{
    if ((m_objFarEnd.GetProtocol() != SipTransportAddress::PROTOCOL_TCP) &&
            (m_objFarEnd.GetProtocol() != SipTransportAddress::PROTOCOL_TLS))
    {
        IMS_TRACE_E(0, "Transport :: Protocol does not use TCP", 0, 0, 0);
        return IMS_NULL;
    }

    SipSocket* pSocket = IMS_NULL;
    // RFC5626_FLOW_CONTROL
    IMS_SINT32 nTempPortC = m_nNearEndPortC;

    if (IsFlowControlPortConfigured())
    {
        IMS_TRACE_D("Transport :: Flow control (%d >> %d) will be applied", nTempPortC,
                m_nPortFlowControl, 0);

        nTempPortC = m_nPortFlowControl;
    }

    SipTransportHelper* pTransportHelper = GetTransportHelper();

    SipSocketAddress objSockAddr;
    objSockAddr.SetIpAddress(m_objNearEnd.GetIpAddress());
    objSockAddr.SetPort(nTempPortC);

    if ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS))
    {
        SipSocketAddress objSockAddrFarEnd;

        objSockAddr.SetType(SipSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        objSockAddrFarEnd.SetIpAddress(m_objFarEnd.GetIpAddress());
        objSockAddrFarEnd.SetPort(m_objFarEnd.GetPort());
        objSockAddrFarEnd.SetType(SipSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        // First, check the accepted TCP connection to re-use the TCP connection
        pSocket = pTransportHelper->OpenStreamSocket(objSockAddr, objSockAddrFarEnd);

        objSockAddr.SetType(SipSocketAddress::SOCKET_TCP_CLIENT);
        objSockAddrFarEnd.SetType(SipSocketAddress::SOCKET_TCP_CLIENT);

        if (pSocket == IMS_NULL)
        {
            pSocket = pTransportHelper->OpenStreamSocket(objSockAddr, objSockAddrFarEnd);
        }

        if ((pSocket == IMS_NULL) && IsFlowControlPortConfigured() &&
                IsTransactionFlowControlRequired())
        {
            IMS_TRACE_D("Transport :: TCP client (%s, %d) can't be created by flow control",
                    SipDebug::GetIp(objSockAddr.GetIpAddress()), objSockAddr.GetPort(), 0);
            return IMS_NULL;
        }

        // TCP client socket
        //  1) The address will be used as the listening point's one.
        //  2) The port number will be generated by the socket library of the system.

        // For port range configuration
        IMS_SINT32 nTcpPortC = 0;

        if ((pSocket == IMS_NULL) && !IsIpSecRequired() && !IsFlowControlPortConfigured() &&
                !IsTcpConnectionOnlyRequired())
        {
            if (SipRtConfigUtils::IsTcpPortRangeConfigured(GetSlotId()))
            {
                const SipPortManager* pPortMngr = SipPortManager::GetInstance();

                if (pPortMngr->IsPortCProvisioned())
                {
                    // Make a local port number to zero to re-use the existing TCP socket.
                    if (nTempPortC == m_objNearEnd.GetPort())
                    {
                        objSockAddr.SetPort(0);
                    }

                    pSocket = pTransportHelper->OpenStreamSocket(objSockAddr, objSockAddrFarEnd);

                    if (pSocket == IMS_NULL)
                    {
                        nTcpPortC = pPortMngr->GetPortC(objSockAddr.GetIpAddress());
                    }
                }
            }
        }

        if (pSocket == IMS_NULL)
        {
            if (nTcpPortC > 0)
            {
                objSockAddr.SetPort(nTcpPortC);
            }
            else if (nTempPortC != m_objNearEnd.GetPort())
            {
                objSockAddr.SetPort(nTempPortC);
            }
            else
            {
                if (IsTcpConnectionOnlyRequired())
                {
                    IMS_TRACE_D("Transport :: TCP client connection is only required...", 0, 0, 0);
                    objSockAddr.SetPort(nTempPortC);
                }
                else if (IsFlowControlPortConfigured())
                {
                    IMS_TRACE_D("Transport :: Flow control is required", 0, 0, 0);
                    objSockAddr.SetPort(nTempPortC);
                }
            }

            // If the transport protocol is TLS, SSL socket will be created...
            if (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS)
            {
                objSockAddr.SetSecure(IMS_TRUE);
            }

            pSocket = pTransportHelper->CreateStreamSocket(objSockAddr, objSockAddrFarEnd);

            if (pSocket == IMS_NULL)
            {
                // LOG_EXCLUDING_SERVER_INFO
                IMS_TRACE_E(0, "Creating TCP client (FAR - %s, %d)",
                        SipRtConfigUtils::IsRoutingInfoHiddenInLog(GetSlotId())
                                ? "xxx"
                                : SipDebug::GetIp(objSockAddrFarEnd.GetIpAddress()),
                        objSockAddrFarEnd.GetPort(), 0);
                return IMS_NULL;
            }

            IMS_TRACE_D("Transport :: TCP client (%s, %d) is created",
                    SipDebug::GetIp(objSockAddr.GetIpAddress()), objSockAddr.GetPort(), 0);
        }
        else
        {
            IMS_TRACE_D("Transport :: TCP client (%s, %d) is re-used (port-c=%d)",
                    SipDebug::GetIp(objSockAddr.GetIpAddress()), objSockAddr.GetPort(), nTempPortC);
        }
    }

    return pSocket;
}

PUBLIC
IMS_BOOL SipTransport::EncodeMessage(IN_OUT ::SipMessage*& pSipMsg, OUT ByteArray& objBuffer)
{
    RcPtr<SipMessageBuffer> pMessageBuffer = SipMessageBuffer::GetInstance();
    IMS_SINT32 nBuffLen = pMessageBuffer->GetLength();
    IMS_BYTE* pBuffer = pMessageBuffer->GetBuffer(GetSlotId());

    IMS_MEM_Memset(pBuffer, 0x00, nBuffLen);

    if (!SipStack::EncodeMessage(pSipMsg, SipPrivate::GetEncodingOptions(), pBuffer, nBuffLen))
    {
        return IMS_FALSE;
    }

    objBuffer.Append(pBuffer, nBuffLen);

    return IMS_TRUE;
}

PUBLIC
const SipTransportAddress& SipTransport::GetAddress(IN IMS_SINT32 nTaType /*= TA_NEAR*/) const
{
    if (nTaType == TA_NEAR)
    {
        return m_objNearEnd;
    }
    else
    {
        return m_objFarEnd;
    }
}

PUBLIC
const IpAddress& SipTransport::GetIpAddress(IN IMS_SINT32 nTaType /*= TA_NEAR*/)
{
    if (nTaType == TA_NEAR)
    {
        return m_objNearEnd.GetIpAddress();
    }
    else
    {
        return m_objFarEnd.GetIpAddress();
    }
}

PUBLIC
IMS_SINT32 SipTransport::GetPort(IN IMS_SINT32 nTaType /*= TA_NEAR*/) const
{
    if (nTaType == TA_NEAR)
    {
        return m_objNearEnd.GetPort();
    }
    else
    {
        return m_objFarEnd.GetPort();
    }
}

PUBLIC
IMS_SINT32 SipTransport::GetProtocol(IN IMS_SINT32 nTaType /*= TA_NEAR*/) const
{
    if (nTaType == TA_NEAR)
    {
        return m_objNearEnd.GetProtocol();
    }
    else
    {
        return m_objFarEnd.GetProtocol();
    }
}

PUBLIC
IMS_BOOL SipTransport::InitTransportDetails(
        IN const SipTransport* pTransport, IN const SipProfile* pProfile /*= IMS_NULL*/)
{
    if (pTransport == IMS_NULL)
    {
        return IMS_FALSE;
    }

    m_bExplicitTargetProtocol = pTransport->m_bExplicitTargetProtocol;
    m_bTxnFlowControlRequired = pTransport->m_bTxnFlowControlRequired;
    m_nNearEndPortC = pTransport->m_nNearEndPortC;
    m_objNearEnd = pTransport->m_objNearEnd;
    m_objFarEnd = pTransport->m_objFarEnd;

    // MULTI_REG_TRANSPORT
    m_nTransportExt = pTransport->m_nTransportExt;
    // RFC5626_FLOW_CONTROL
    m_nPortFlowControl = pTransport->m_nPortFlowControl;

    if (!ReserveResource(pProfile))
    {
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

PUBLIC
IMS_BOOL SipTransport::InitTransportOnMessageReceived(IN ::SipMessage* /*pSipMsg*/)
{
    if (m_nType == TYPE_CLIENT)
    {
        InitRetransmissionFlag();
    }

    return IMS_TRUE;
}

PUBLIC
void SipTransport::NotifyTransactionTimeout()
{
    if (!IsFlowControlPortConfigured() && !IsTcpConnectionOnlyRequired() &&
            GetTransportHelper()->IsSocketPresent(m_pSocket) &&
            m_pSocket->GetType() == SipSocketAddress::SOCKET_TCP_CLIENT)
    {
        // If SIP transaction timeout occurs and a client-initiated TCP connection exists,
        // close the TCP socket so that new SIP requests can use the newly created socket.
        SipStreamSocket* pStreamSocket = static_cast<SipStreamSocket*>(m_pSocket);

        if (pStreamSocket->IsKeepAlivePermanent() || pStreamSocket->IsKeepAliveTimerActive())
        {
            IMS_TRACE_I("NotifyTransactionTimeout: TCP connection is ready to close", 0, 0, 0);
            // Allow the socket close when the transport is being destroyed.
            pStreamSocket->SetKeepAlivePolicy(0);
        }
    }
}

PUBLIC
IMS_BOOL SipTransport::SendToNetwork(IN const IMS_BYTE* pBuffer, IN IMS_SINT32 nBuffLen,
        IN const SipProfile* pProfile, IN IMS_BOOL bNotifyError /*= IMS_TRUE*/)
{
    // Find a socket to send an SIP message, and if not found, try to create a new socket.
    m_pSocket = (m_pSocket == IMS_NULL) ? LookupSocket() : m_pSocket;

    if (GetTransportHelper()->IsSocketPresent(m_pSocket) && m_pSocket->IsClosedOrBeingClosed())
    {
        IMS_TRACE_D("Socket is already closed or being closed", 0, 0, 0);
        ReleaseSocket();
    }

    if (m_pSocket == IMS_NULL)
    {
        ReserveResource(pProfile);

        if (m_pSocket == IMS_NULL)
        {
            IMS_TRACE_E(0, "Can't find a proper SIP socket from the transport layer.", 0, 0, 0);
            goto EXIT_SendToNetwork;
        }
    }

    // For an initial TCP client connection...
    if (!m_pSocket->Connect())
    {
        IMS_TRACE_E(0, "Connecting transport channel failed ...", 0, 0, 0);
        goto EXIT_SendToNetwork;
    }

    if (m_pSocket->GetState() != SipSocket::STATE_CONNECTED)
    {
        IMS_TRACE_D("___ Waiting the establishment of transport channel ...", 0, 0, 0);

        if (m_pSendBuffer != IMS_NULL)
        {
            delete m_pSendBuffer;
        }

        m_pSendBuffer = new ByteArray(pBuffer, nBuffLen);

        return IMS_TRUE;
    }

    if (!TransmitMessage(pBuffer, nBuffLen))
    {
        IMS_TRACE_E(0, "Transmitting SIP message to the destination (%s:%d) failed",
                SipDebug::GetIp(m_objFarEnd.GetIpAddress()), m_objFarEnd.GetPort(), 0);
        goto EXIT_SendToNetwork;
    }

    m_bIsRetransmission = IMS_TRUE;

    return IMS_TRUE;

EXIT_SendToNetwork:
    if (bNotifyError && m_bIsRetransmission && (m_piListener != IMS_NULL))
    {
        AString strError;

        strError.Sprintf("%d Message retransmission failed", SipError::TRANSPORT_E_CODE_107);
        m_piListener->Transport_NotifyError(SipSocket::ERROR_SEND_FAILED, strError);
    }

    return IMS_FALSE;
}

PUBLIC
void SipTransport::SetAddress(
        IN const SipTransportAddress& objTAddr, IN IMS_SINT32 nTaType /*= TA_NEAR*/)
{
    if (nTaType == TA_NEAR)
    {
        m_objNearEnd = objTAddr;
    }
    else
    {
        m_objFarEnd = objTAddr;
    }
}

PUBLIC
void SipTransport::SetIpAddress(IN const IpAddress& objIp, IN IMS_SINT32 nTaType /*= TA_NEAR*/)
{
    if (nTaType == TA_NEAR)
    {
        m_objNearEnd.SetIpAddress(objIp);
    }
    else
    {
        m_objFarEnd.SetIpAddress(objIp);
    }
}

PUBLIC
void SipTransport::SetPort(IN IMS_SINT32 nPort, IN IMS_SINT32 nTaType /*= TA_NEAR*/)
{
    if (nTaType == TA_NEAR)
    {
        m_objNearEnd.SetPort(nPort);
    }
    else
    {
        m_objFarEnd.SetPort(nPort);
    }
}

PUBLIC
void SipTransport::SetProtocol(IN IMS_SINT32 nProtocol, IN IMS_SINT32 nTaType /*= TA_NEAR*/)
{
    if (nTaType == TA_NEAR)
    {
        m_objNearEnd.SetProtocol(nProtocol);
    }
    else
    {
        m_objFarEnd.SetProtocol(nProtocol);
    }
}

// RFC5626_FLOW_CONTROL, MULTI_REG_TRANSPORT
PUBLIC
void SipTransport::SetTransportTuple(IN const IpAddress& objIp, IN IMS_SINT32 nPortS,
        IN IMS_SINT32 nPortC, IN IMS_SINT32 nPortFc /*= Sip::PORT_UNSPECIFIED*/,
        IN IMS_SINT32 nTransportExt /*= Sip::TRANSPORT_EXT_ANY*/)
{
    m_objNearEnd.SetIpAddress(objIp);
    m_objNearEnd.SetPort(nPortS);

    m_nNearEndPortC = nPortC;

    // RFC5626_FLOW_CONTROL
    m_nPortFlowControl = nPortFc;

    // MULTI_REG_TRANSPORT
    m_nTransportExt = nTransportExt;

    IMS_TRACE_D("SetTransportTuple: port-c=%d, port-fc=%d, transportExt=%08X", nPortC, nPortFc,
            nTransportExt);
}

PUBLIC
void SipTransport::StoreResource()
{
    // Store the socket if and only if the transport protocol is TCP
    if ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS))
    {
        SipSocketAddress objSockAddr;
        SipSocketAddress objSockAddrFarEnd;

        objSockAddr.SetIpAddress(m_objNearEnd.GetIpAddress());
        objSockAddr.SetPort(m_objNearEnd.GetPort());
        objSockAddr.SetType(SipSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        objSockAddrFarEnd.SetIpAddress(m_objFarEnd.GetIpAddress());
        objSockAddrFarEnd.SetPort(m_objFarEnd.GetPort());
        objSockAddrFarEnd.SetType(SipSocketAddress::SOCKET_TCP_CLIENT_BY_PEER);

        // First, check the accepted TCP connection to re-use the TCP connection
        m_pSocket = GetTransportHelper()->OpenStreamSocket(objSockAddr, objSockAddrFarEnd);

        if (m_pSocket != IMS_NULL)
        {
            m_pSocket->SetListener(this);

            IMS_TRACE_D("Transport :: TCP connection is bound", 0, 0, 0);
        }
    }
}

PUBLIC VIRTUAL IMS_BOOL SipTransport::ReserveResource(IN const SipProfile* pProfile /*= IMS_NULL*/)
{
    if (!IsNetworkConnectionAvailable())
    {
        return IMS_FALSE;
    }

    // Check the validity of transport information (Type of transport & port number)

    // Reserve the socket resource
    if (!ReserveSocket(pProfile))
    {
        ReleaseSocket();
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

PUBLIC GLOBAL AString SipTransport::CreateSocketErrorMessage(
        IN IMS_SINT32 nErrorCode, IN IMS_SINT32 nSocketType /*= SipSocketAddress::SOCKET_NONE*/)
{
    AString strError(AString::ConstNull());

    switch (nErrorCode)
    {
        case SipSocket::ERROR_CLOSED:
            // SIP_TRANSPORT_ERROR_REPORT_ON_TXN
            if (nSocketType == SipSocketAddress::SOCKET_TCP_CLIENT)
            {
                strError.Sprintf("%d Socket is closed by peer", SipError::TRANSPORT_E_CODE_104);
            }
            break;

        case SipSocket::ERROR_CONNECT_FAILED:
            strError.Sprintf("%d Socket connect failed", SipError::TRANSPORT_E_CODE_105);
            break;

        case SipSocket::ERROR_DATA_CONNECTION_LOST:
            strError.Sprintf("%d Socket is abnormally closed", SipError::TRANSPORT_E_CODE_106);
            break;

        case SipSocket::ERROR_WOULDBLOCK_TIMEDOUT:
            strError.Sprintf("%d Too long wouldblock", SipError::TRANSPORT_E_CODE_101);
            break;

        case SipSocket::ERROR_CONNECTION_TIMEDOUT:
            strError.Sprintf("%d TCP connection timed out", SipError::TRANSPORT_E_CODE_102);
            break;

        default:
            break;
    }

    return strError;
}

PUBLIC GLOBAL IMS_BOOL SipTransport::GetHostNPortFromViaHeader(
        IN ::SipMessage* pSipMsg, OUT AString& strHost, OUT IMS_SINT32& nPort)
{
    return SipStack::GetHostNPortFromViaHeader(pSipMsg, strHost, nPort);
}

PUBLIC GLOBAL void SipTransport::ParseHostNPort(
        IN const AString& strHostNPort, OUT AString& strHost, OUT IMS_SINT32& nPort)
{
    SipStack::ParseHostNPort(strHostNPort, strHost, nPort);
}

PUBLIC GLOBAL void SipTransport::PrintMessage(IN IMS_SINT32 nSlotId, IN IMS_BOOL bSend,
        IN const SipTransportAddress& objFarEnd, IN const IMS_CHAR* pszMessage,
        IN IMS_SINT32 nLength)
{
    // SEND or RECV:Message Length:Transport Type:IP address:Port
    // For example,
    //    SEND:    <<<==SEND:512:UDP:10.168.114.153:5060==
    //    RECV:    ==RECV:512:TCP:10.168.114.153:5060==>>>
    const IMS_CHAR* pszFormat;
    const IMS_CHAR* pszTransport;
    AString strLog;

    // Summary of message -- starts

    if (bSend)
    {
        pszFormat = "<<<==SEND:%d:%s:%s:%d_s%d==";
    }
    else
    {
        pszFormat = "==RECV:%d:%s:%s:%d_s%d==>>>";
    }

    if (objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_UDP)
    {
        pszTransport = Sip::STR_UDP_CAPS;
    }
    else if (objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP)
    {
        pszTransport = Sip::STR_TCP_CAPS;
    }
    else if (objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS)
    {
        pszTransport = Sip::STR_TLS_CAPS;
    }
    else
    {
        pszTransport = "UNKNOWN";
    }

    // LOG_EXCLUDING_SERVER_INFO
    if (SipRtConfigUtils::IsMessageHiddenInLog(nSlotId))
    {
        strLog.Sprintf(pszFormat, nLength, pszTransport,
                objFarEnd.GetIpAddress().IsIPv6Address() ? "::" : "0.0.0.0", objFarEnd.GetPort(),
                nSlotId);
    }
    else
    {
        strLog.Sprintf(pszFormat, nLength, pszTransport, SipDebug::GetIp(objFarEnd.GetIpAddress()),
                objFarEnd.GetPort(), nSlotId);
    }

    // Summary of message -- ends

    // Display whole SIP message
    // LOG_EXCLUDING_SERVER_INFO
    if (SipRtConfigUtils::IsMessageHiddenInLog(nSlotId))
    {
        IMS_TRACE_SIP(strLog.GetStr(), pszMessage, (nLength < 11) ? nLength : 11);
    }
    else
    {
        IMS_TRACE_SIP(strLog.GetStr(), pszMessage, nLength);
    }
}

PROTECTED VIRTUAL void SipTransport::Socket_NotifyError(
        IN SipSocket* pSocket, IN IMS_SINT32 nErrorCode)
{
    if (m_pSocket != pSocket)
    {
        IMS_TRACE_D("Socket_NotifyError() :: Socket not matched", 0, 0, 0);
        return;
    }

    IMS_BOOL bIgnoreClosedOrConnectFailed = (m_pSocket == IMS_NULL);
    IMS_SINT32 nSocketType =
            (m_pSocket != IMS_NULL) ? m_pSocket->GetType() : SipSocketAddress::SOCKET_NONE;

    if (m_pSendBuffer != IMS_NULL)
    {
        delete m_pSendBuffer;
        m_pSendBuffer = IMS_NULL;
    }

    ReleaseSocket();
    NotifyTransportError(nErrorCode, nSocketType, bIgnoreClosedOrConnectFailed);
}

PROTECTED VIRTUAL void SipTransport::Socket_SendEnabled(IN SipSocket* pSocket)
{
    (void)pSocket;

    if (m_pSocket == IMS_NULL)
    {
        // Do nothing...
        IMS_TRACE_D("Socket NULL", 0, 0, 0);
        return;
    }

    if (m_pSocket != pSocket)
    {
        // Do nothing...
        IMS_TRACE_D("Socket not matched", 0, 0, 0);
        return;
    }

    if (m_pSocket->GetState() != SipSocket::STATE_CONNECTED)
    {
        // Do nothing ...
        IMS_TRACE_D("Socket is not ready", 0, 0, 0);
        return;
    }

    // In case of UDP transport, if the socket is created at the first, the below operation needs.
    if (m_pSendBuffer != IMS_NULL)
    {
        if (!TransmitMessage(m_pSendBuffer->GetData(), m_pSendBuffer->GetLength()))
        {
            if (m_piListener != IMS_NULL)
            {
                AString strError;

                strError.Sprintf("%d Message transmission failed", SipError::TRANSPORT_E_CODE_103);
                m_piListener->Transport_NotifyError(SipSocket::ERROR_SEND_FAILED, strError);
            }
        }
        else
        {
            // If this message(first message) is successfully sent,
            // then the retransmission flag will be set in here.
            m_bIsRetransmission = IMS_TRUE;

            // The pending message is completely sent.
            if (m_pSendBuffer == IMS_NULL)
            {
                if (m_piListener != IMS_NULL)
                {
                    m_piListener->Transport_NotifyPendingMessageSent();
                }
            }
        }
    }
}

PROTECTED
void SipTransport::CorrectNearEndAddress()
{
    // Correct the port number with a default port if it does not explicitly
    if (m_objNearEnd.GetPort() == Sip::PORT_UNSPECIFIED)
    {
        if (m_objNearEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS)
        {
            m_objNearEnd.SetPort(Sip::PORT_5061);
        }
        else
        {
            m_objNearEnd.SetPort(Sip::PORT_5060);
        }
    }
}

PROTECTED
SipTransportHelper* SipTransport::GetTransportHelper() const
{
    return SipFactoryProxy::GetInstance()->GetTransportHelper(GetSlotId());
}

PROTECTED
void SipTransport::NotifyTransportError(IN IMS_SINT32 nErrorCode)
{
    IMS_SINT32 nSocketType =
            (m_pSocket != IMS_NULL) ? m_pSocket->GetType() : SipSocketAddress::SOCKET_NONE;
    NotifyTransportError(nErrorCode, nSocketType, (m_pSocket == IMS_NULL));
}

PROTECTED
void SipTransport::NotifyTransportError(IN IMS_SINT32 nErrorCode, IN IMS_SINT32 nSocketType,
        IN IMS_BOOL bIgnoreClosedOrConnectFailed)
{
    if (m_piListener == IMS_NULL)
    {
        IMS_TRACE_D("Transport :: No Listener, Error (%d)", nErrorCode, 0, 0);
        return;
    }

    IMS_TRACE_D("Transport :: Error (%d)", nErrorCode, 0, 0);

    switch (nErrorCode)
    {
        case SipSocket::ERROR_CLOSED:          // FALL-THROUGH
        case SipSocket::ERROR_CONNECT_FAILED:  // FALL-THROUGH
        case SipSocket::ERROR_DATA_CONNECTION_LOST:
            if (bIgnoreClosedOrConnectFailed)
            {
                // no-op
                return;
            }
            break;
        default:
            break;
    }

    AString strError = CreateSocketErrorMessage(nErrorCode, nSocketType);

    if (strError.GetLength() > 0)
    {
        m_piListener->Transport_NotifyError(SipError::TRANSPORT_ERROR, strError);
    }
}

PRIVATE
IMS_BOOL SipTransport::IsNetworkConnectionAvailable() const
{
    if (NetworkService::GetNetworkService()->FindConnection(m_objNearEnd.GetIpAddress()) ==
            IMS_NULL)
    {
        IMS_TRACE_E(0, "Network (%s) is not available",
                SipDebug::GetIp(m_objNearEnd.GetIpAddress()), 0, 0);
        return IMS_FALSE;
    }

    return IMS_TRUE;
}

PRIVATE
SipSocket* SipTransport::LookupSocket() const
{
    SipTransportHelper* pTransportHelper = GetTransportHelper();
    SipSocketAddress objSockAddr;

    if ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS))
    {
        SipSocketAddress objSockAddrFarEnd;

        objSockAddr.SetIpAddress(m_objNearEnd.GetIpAddress());
        objSockAddr.SetPort(m_nNearEndPortC);
        objSockAddr.SetType(SipSocketAddress::SOCKET_TCP_CLIENT);

        objSockAddrFarEnd.SetIpAddress(m_objFarEnd.GetIpAddress());
        objSockAddrFarEnd.SetPort(m_objFarEnd.GetPort());
        objSockAddrFarEnd.SetType(SipSocketAddress::SOCKET_TCP_CLIENT);

        return pTransportHelper->OpenStreamSocket(objSockAddr, objSockAddrFarEnd);
    }
    else
    {
        objSockAddr.SetIpAddress(m_objNearEnd.GetIpAddress());
        objSockAddr.SetPort(m_nNearEndPortC);
        objSockAddr.SetType(SipSocketAddress::SOCKET_UDP);

        return pTransportHelper->Open(objSockAddr);
    }
}

PRIVATE
void SipTransport::ReleaseSocket()
{
    if (m_pSocket != IMS_NULL)
    {
        GetTransportHelper()->Destroy(m_pSocket, this);
        m_pSocket = IMS_NULL;
    }
}

PRIVATE
IMS_BOOL SipTransport::ReserveSocket(IN const SipProfile* pProfile /*= IMS_NULL*/)
{
    // RFC5626_FLOW_CONTROL
    IMS_SINT32 nTempPortC = m_nNearEndPortC;

    if (IsFlowControlPortConfigured())
    {
        IMS_TRACE_D("Transport :: Flow control (%d >> %d) will be applied", nTempPortC,
                m_nPortFlowControl, 0);

        nTempPortC = m_nPortFlowControl;
    }

    // If the transport has already the connected socket, do not reserve the socket again.
    if (GetTransportHelper()->IsSocketPresent(m_pSocket))
    {
        // Check if the port is same or not...
        if (m_nType != TYPE_CLIENT)
        {
            // In case of server transport & TCP protocol used
            IMS_TRACE_D(
                    "Transport :: server transport will use an existing TCP connection", 0, 0, 0);
            return IMS_TRUE;
        }

        IpAddress objIp;
        IMS_UINT32 nPort = 0;
        IMS_BOOL bCheckTcpSocketReusability = IMS_FALSE;

        m_pSocket->GetSockName(objIp, nPort);

        if (nTempPortC == static_cast<IMS_SINT32>(nPort))
        {
            if ((m_pSocket->GetType() == SipSocketAddress::SOCKET_UDP) &&
                    (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_UDP))
            {
                // If the port is same, the socket will be re-used...
                IMS_TRACE_D("Transport :: UDP client (%s, %d) is re-used", SipDebug::GetIp(objIp),
                        nPort, 0);
                return IMS_TRUE;
            }
            else if ((m_pSocket->GetType() == SipSocketAddress::SOCKET_TCP_CLIENT) &&
                    ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
                            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS)))
            {
                bCheckTcpSocketReusability = IMS_TRUE;
            }
        }
        // Case: random port number for TCP connection
        else if ((nTempPortC == 0) || (nTempPortC == m_objNearEnd.GetPort()))
        {
            if ((m_pSocket->GetType() == SipSocketAddress::SOCKET_TCP_CLIENT) &&
                    ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
                            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS)))
            {
                bCheckTcpSocketReusability = IMS_TRUE;
            }
        }

        if (bCheckTcpSocketReusability)
        {
            IpAddress objPeerIp;
            IMS_UINT32 nPeerPort = 0;

            m_pSocket->GetPeerName(objPeerIp, nPeerPort);

            if (objPeerIp.Equals(m_objFarEnd.GetIpAddress()) &&
                    (m_objFarEnd.GetPort() == static_cast<IMS_SINT32>(nPeerPort)))
            {
                // If the port is same, the socket will be re-used...
                IMS_TRACE_D("Transport :: TCP client (%s, %d) is re-used", SipDebug::GetIp(objIp),
                        nPort, 0);

                // MULTI_REG_SIP_PROFILE
                SipStreamSocket* pStreamSocket = DYNAMIC_CAST(SipStreamSocket*, m_pSocket);

                pStreamSocket->SetConfigForSipKeepAlive(
                        SipConfigProxy::IsKeepAliveConfigured(GetSlotId(), pProfile));
                return IMS_TRUE;
            }
            else
            {
                IMS_TRACE_D("Transport :: TCP client (%s, %d) is matched", SipDebug::GetIp(objIp),
                        nPort, 0);
                // LOG_EXCLUDING_SERVER_INFO
                IMS_TRACE_D("Transport :: TCP client (peer) (%s, %d) is not matched",
                        SipRtConfigUtils::IsRoutingInfoHiddenInLog(GetSlotId())
                                ? "xxx"
                                : SipDebug::GetIp(objPeerIp),
                        nPeerPort, 0);
            }
        }

        // Release the previous socket and create a new socket...
        ReleaseSocket();
    }

    if ((m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TCP) ||
            (m_objFarEnd.GetProtocol() == SipTransportAddress::PROTOCOL_TLS))
    {
        m_pSocket = CreateTcpClientSocket();

        if (m_pSocket == IMS_NULL)
        {
            return IMS_FALSE;
        }

        SipStreamSocket* pStreamSocket = DYNAMIC_CAST(SipStreamSocket*, m_pSocket);

        // RFC5626_FLOW_CONTROL
        if (IsFlowControlPortConfigured())
        {
            if (!pStreamSocket->IsKeepAlivePermanent())
            {
                pStreamSocket->SetKeepAlivePolicy(SipConfig::TcpTimerValues::PERMANENT);
            }
        }

        // MULTI_REG_SIP_PROFILE
        pStreamSocket->SetConfigForSipKeepAlive(
                SipConfigProxy::IsKeepAliveConfigured(GetSlotId(), pProfile));
    }
    else
    {
        SipSocketAddress objSockAddr;
        objSockAddr.SetIpAddress(m_objNearEnd.GetIpAddress());
        objSockAddr.SetPort(nTempPortC);

        // Open the UDP client socket
        objSockAddr.SetType(SipSocketAddress::SOCKET_UDP);

        m_pSocket = GetTransportHelper()->Create(objSockAddr);

        if (m_pSocket == IMS_NULL)
        {
            IMS_TRACE_E(0, "Creating UDP client (%s, %d)",
                    SipDebug::GetIp(objSockAddr.GetIpAddress()), objSockAddr.GetPort(), 0);
            return IMS_FALSE;
        }

        IMS_TRACE_D("Transport :: UDP client (%s, %d) is created",
                SipDebug::GetIp(objSockAddr.GetIpAddress()), objSockAddr.GetPort(), 0);
    }

    m_pSocket->SetListener(this);

    return IMS_TRUE;
}

PRIVATE
IMS_BOOL SipTransport::TransmitMessage(IN const IMS_BYTE* pBuffer, IN IMS_SINT32 nBuffLen)
{
    // If SIP TX packet is blocked by the application,
    // don't send the packet via Socket.
    if (SipRtConfigUtils::IsFeatureSipTxPacketBlockedEnabled(GetSlotId()))
    {
        PrintMessage(GetSlotId(), IMS_TRUE, m_objFarEnd, reinterpret_cast<const IMS_CHAR*>(pBuffer),
                nBuffLen);
        return IMS_TRUE;
    }

    IMS_SINT32 nSentBytes =
            m_pSocket->Send(pBuffer, nBuffLen, m_objFarEnd.GetPort(), m_objFarEnd.GetIpAddress());

    // DEBUGGING message ...
    {
        PrintMessage(GetSlotId(), IMS_TRUE, m_objFarEnd, reinterpret_cast<const IMS_CHAR*>(pBuffer),
                nBuffLen);
    }

    if (nSentBytes == ISocket::RESULT_ERROR)
    {
        if (m_pSendBuffer != IMS_NULL)
        {
            delete m_pSendBuffer;
            m_pSendBuffer = IMS_NULL;
        }

        IMS_TRACE_E(0, "Sending SIP message to the network failed", 0, 0, 0);
        return IMS_FALSE;
    }
    else if (nSentBytes < nBuffLen)
    {
        ByteArray objBuffer;

        objBuffer.Append(&pBuffer[nSentBytes], nBuffLen - nSentBytes);

        if (m_pSendBuffer != IMS_NULL)
        {
            delete m_pSendBuffer;
        }

        m_pSendBuffer = new ByteArray(objBuffer);
    }
    else
    {
        if (m_pSendBuffer != IMS_NULL)
        {
            delete m_pSendBuffer;
            m_pSendBuffer = IMS_NULL;
        }
    }

    IMS_TRACE_I("___ SipTransport - SENT BYTES (%d) ___", nSentBytes, 0, 0);

    return IMS_TRUE;
}
