/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INTERFACE_MTS_SERVICE_H_
#define INTERFACE_MTS_SERVICE_H_

#include "ByteArray.h"
#include "ImsTypeDef.h"
#include "MtsDef.h"

class ICoreService;
class IMtsServiceState;

class IMtsService
{
public:
    virtual ~IMtsService() {}

    /**
     * @brief Gets the ICoreService object.
     *
     * @return The ICoreService object.
     */
    virtual ICoreService* GetICoreService() const = 0;

    /**
     * @brief Gets the IMtsServiceState object.
     *
     * @return The IMtsServiceState object.
     */
    virtual IMtsServiceState* GetIMtsServiceState() const = 0;

    /**
     * @brief Requests the IMS registration recovery procedure.
     *
     * @param nRecoveryType Indicate the control type for registration. (@see ImsAosControl)
     */
    virtual void RequestRegistrationRecovery(IN IMS_UINT32 nRecoveryType) const = 0;

    /**
     * @brief Calls the AoS to register with next P-CSCF.
     *
     * @param nRetryAfterValue The value of the Retry-After header received.
     */
    virtual void RequestRegisterWithNextPcscf(IN const IMS_UINT32 nRetryAfterValue) const = 0;

    /**
     * @brief Sends a request for a mobile originated SMS, checking IMS traffic.
     *
     * This function initiates the process of sending a mobile originated (MO) SMS.
     * It ensures that the SMS is sent through the IMS network and handles necessary
     * checks related to IMS traffic.
     *
     * @param eSmsFormat The format of the SMS.
     * @param pContent A pointer to the protocol data unit (PDU).
     * @param strAddress The address to send the SMS to.
     * @param nSeqId The unique token generated by the platform that should be used when triggering
     *               callbacks for this specific message.
     * @param bEmergency {@code IMS_TRUE} If the dialed number is an emergency number,
     *                   {@code IMS_FALSE} otherwise.
     * @param nRetryCount The SMS retry count, controlled by the upper layer.
     */
    virtual void SendMoSms(IN SmsFormatType eSmsFormat, IN ByteArray* pContent,
            IN const AString& strAddress, IN IMS_SINT32 nSeqId, IN IMS_BOOL bEmergency,
            IN IMS_UINT32 nRetryCount) = 0;
};

#endif
