#ifndef CONFERENCE_DEF_H_
#define CONFERENCE_DEF_H_

//
enum
{
    REFERENCE_TYPE_INVALID = -1,
    REFERENCE_TYPE_INVITE = 0,
    REFERENCE_TYPE_BYE = 1
};

enum
{
    CONTROL_OPERATION_NONE = 0,
    CONTROL_OPERATION_CREATE_CONFERENCE_SESSION = 1,
    CONTROL_OPERATION_SUBSCRIBE = 2,
    CONTROL_OPERATION_UNSUBSCRIBE = 3,
    CONTROL_OPERATION_REFER_INVITE = 4,
    CONTROL_OPERATION_REFER_BYE = 5,
    CONTROL_OPERATION_CHECK_CONNECTED = 6,
    CONTROL_OPERATION_NOTIFY_RESULT_TO_UI = 7,
    CONTROL_OPERATION_TERMINATE_1TO1_SESSION = 8,
    CONTROL_OPERATION_TERMINATE_CONFERENCE = 9,
    CONTROL_OPERATION_DESTROY_CONTROLLER = 10,
    CONTROL_OPERATION_NOTIFY_RESULT_TO_UCSESSION = 11
};

// TODO: align with CONFINFO_STATUS....?
enum
{
    STATUS_INVALID = 0,
    STATUS_PROGRESSING = 1,
    STATUS_CONNECTED = 2,
    STATUS_DISCONNECTED = 3,
    STATUS_ON_HOLD = 4,
    STATUS_MUTED_VIA_FOCUS = 5,
    STATUS_PENDING = 6,
    STATUS_ALERTING = 7,
    STATUS_DIALING_IN = 8,
    STATUS_DIALING_OUT = 9,
    STATUS_DISCONNECTING = 10,

    STATUS_FAIL = 20,
    STATUS_REJECT = 21,
    STATUS_BUSY = 22,
    STATUS_SERVERERROR = 23,
    STATUS_NOTSUPPORTED = 24,
    STATUS_NOTACCEPTABLE = 25,
    STATUS_NOANSWER = 26,
    STATUS_NOTREACHABLE = 27,
    STATUS_LOWBATTERY = 28,
    STATUS_FORBIDDEN = 29,
    STATUS_INTSERVERERROR = 30
};

/*
UCSessDef::CONFINFO_STATUS

    CONFINFO_STATUS_PROGRESSING             = 1, //ByConfMngr, Intrtnal information for UX
    CONFINFO_STATUS_CONNECTED               = 2,
    CONFINFO_STATUS_DISCONNECTED            = 3,
    CONFINFO_STATUS_ONHOLD                  = 4,
    CONFINFO_STATUS_MUTEDVIAFOCUS           = 5,
    CONFINFO_STATUS_PENDING                 = 6,
    CONFINFO_STATUS_ALERTING                = 7,
    CONFINFO_STATUS_DIALING_IN              = 8,
    CONFINFO_STATUS_DIALING_OUT             = 9,
    CONFINFO_STATUS_DISCONNECTING           = 10,
*/

enum
{
    CONF_MEDIA_TYPE_AUDIO = 0,
    CONF_MEDIA_TYPE_VIDEO = 1,
    CONF_MEDIA_TYPE_TEXT = 2  // No ???
};

enum
{
    CONF_MEDIA_STATUS_SENDRECV = 0,
    CONF_MEDIA_STATUS_SENDONLY = 1,
    CONF_MEDIA_STATUS_RECVONLY = 2,
    CONF_MEDIA_STATUS_INVALID = 3
};

enum
{
    CONF_SUBSCRIPTION_DIALOG_TYPE_IN = 0,
    CONF_SUBSCRIPTION_DIALOG_TYPE_OUT = 1,
    CONF_SUBSCRIPTION_DIALOG_TYPE_FALLBACK = 2  // IN failed, so OUT is being used.
};

#endif
