#include "ConfigSipDelegate.h"

#define CONFIG_APP_NAME "ims.app.sip_delegate"
#define CONFIG_SERVICE_NAME "ims.service.sip_delegate"

PUBLIC GLOBAL const IMS_CHAR ConfigSipDelegate::APP_NAME[] = CONFIG_APP_NAME;
PUBLIC GLOBAL const IMS_CHAR ConfigSipDelegate::SERVICE_NAME[] = CONFIG_SERVICE_NAME;

PUBLIC GLOBAL const IMS_CHAR ConfigSipDelegate::APP_CONFIG[] = {
        "[Uniqueness]\n"
        "Stream=0\n"
        "Framed=0\n"
        "Basic=0\n"
        "Event=0\n"
        "CoreService=1\n"
        "Qos=0\n"
        "Reg=1\n"
        "Write=1\n"
        "Read=1\n"
        "Cap=0\n"
        "Mprof=0\n"
        "Connection=0\n"
        "\n"
        "[IMSRegistry]\n"
        "IMSRegistry=" CONFIG_APP_NAME "\n"
        "\n"
        "[CoreService_0]\n"
        "service_id=" CONFIG_SERVICE_NAME "\n"
        "iari=\n"
        "icsi=\n"
        "feature_tag=\n"
        "\n"
        "[Reg_0]\n"
        "service_id=" CONFIG_SERVICE_NAME "\n"
        "header_count=1\n"
        "header_0=Supported: path\n"
        "\n"
        "[Write]\n"
        "header_names=\n"
        "\n"
        "[Read]\n"
        "header_names=\n"
        "\n"
};
