/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __SIP_ERROR_H__
#define __SIP_ERROR_H__

#define SIP_ERRORCODES_START     100
#define SIP_ERRORCODES_GAP       100

#define SIP_ERRORCODES_UTILS     (SIP_ERRORCODES_START + (0 * SIP_ERRORCODES_GAP))
#define SIP_ERRORCODES_TXNTRANSP (SIP_ERRORCODES_START + (1 * SIP_ERRORCODES_GAP))
#define SIP_ERRORCODES_MSG       (SIP_ERRORCODES_START + (2 * SIP_ERRORCODES_GAP))

typedef enum _SipEn_ErrorTypes
{
    ESIPUTILERRSTART = SIP_ERRORCODES_UTILS,
    EERR_MALLOCFAILED,
    EERR_LISTINITFAILED,
    EERR_LISTNOMEM,
    EERR_LISTNOTEXIST,
    EERR_LISTELEMENTNOTEXIST,
    EERR_LISTNODENOTEXIST,
    EERR_LISTINVINPUT,
    EERR_LISTFREEFXNNOTSET,
    EERR_LISTNOCOMPAREFXN,
    EERR_NULLPOINTER,
    EERR_INVALIDINPUT,
    EERR_INCOMPLETEMESSAGE,
    EERR_METHODMISMATCH,
    EERR_INVALIDPARAM,
    EERR_HASHELEMENTSEXCEEDED,
    EERR_HASHKEYALREADYEXISTS,
    EERR_HASHELEMENTSNOTFOUND,
    EERR_TIMER_NOTCREATED,
    EERR_TIMER_NOTIMEREXISTS,
    EERR_TIMER_RESETFAIL,
    EERR_TIMER_RESETSUCCESS,
    EERR_MUTEXCREATIONFAILED,
    EERR_MUTEXINITFAILED,
    EERR_NOEXISTS,
    EERR_NOERR,

    /* Hash Errors */
    E_ERR_HASH_INVALIDPARAM,
    E_ERR_HASHELEMENTSNOTFOUND,
    E_ERR_HASHELEMENTSEXCEEDED,
    E_ERR_KEYALREADYEXISTS,

    /*  Memory Management, Timer, Link-List */
    E_ERR_PF_MALLOCFAILED,
    E_ERR_PF_APPENDFAILED,
    E_ERR_TIMER_NOTCREATED,
    E_ERR_TIMER_RESETSUCCESS,
    E_ERR_TIMER_RESETFAIL,

    ESIPTXNTRANSPERRSTART = SIP_ERRORCODES_TXNTRANSP,

    EERR_STACKNOTINITIALIZED, /* Stack Error */
    ETXN_DBERROR,
    ETXN_ALREADYTRANSACTIONINPROCESSERROR = 0,
    ETXN_TRANSMISSIONERROR,      /* Request or Response error, Retransmitting Error */
    ETXN_INTERNALERROR,          /* Error in restarting Timer */
    ETXN_TRANPORTERROR,          /* Event to map the asynchronous error from Transport layer */
    ETXN_TRANSACTIONCREATEERROR, /* Error during start of Transaction */
    ETXN_TRANSACTIONERROR,       /* Error while sending response in server transaction */
    /* When Received Response doesn't find Transaction or
       When User wants to send response and there is no transaction*/
    ETXN_TRANSACTIONNOTFOUNDERROR,
    ETXN_TRANSPORTINFOMISSINGERROR, /* Cannot send a Request in Server Transaction */
    ETXN_TRANSACTIONINVALIDERROR,
    ETXN_TRANSACTION_NOTFOUND,
    ETXN_FSMEVENTERROR,
    /* When TxnInfo is null on fetch from Db is success */
    ETXN_STACKERROR,
    /* Transaction Timeout:UA need to treat this error as
       '408 Request Timeout'*/
    ETXN_TIMEOUTERROR,
    /* Error code for  ICMP Errors for UDP : UA need to
       treat as 503 'Service Unavailable'*/
    ETXN_UDPTRANSPORTERROR,
    ETXN_TCPCONNECTIONERROR, /* TCP Connection Errors */
    ETXN_INVALIDTXNHANDLE,   /* When Handle is Invalid */
    ETRANSP_TYPEERROR,       /* Tranpsort Type Error */
    ETRANSP_MISMATCHERROR,   /* Sent-by Value mismatch with actual sent request*/

    ESIPMSGERRSTART = SIP_ERRORCODES_MSG,

    EMSG_VIAHDRERROR, /* Sent By Value is missing */
    /* Content Length Header is mandatory RFC 3261 Section:
       20.14 Content-Length*/
    EMSG_CONTENTLENHDRMISSINGERROR,
    /* If the transport packet ends before the end of the message body*/
    EMSG_BODYLENERROR,

    /*Decode Errors*/
    ESIPERR_REQLINEDECFAILED,
    ESIPERR_STATUSLINEDECFAILED,

    /* SIP Message Errors */
    E_ERR_HDRNOTIMPLEMENTED,
    E_ERR_INVALIDBODY,
    E_ERR_INVALIDBOUNDARY,
    EMSGERR_INVALIDINPUT,
    EERR_DUPLICATEHDR,
    EMSGERR_UNKNOWNMETHOD,
    EMSGERR_INVALIDMSGTYPE,
    EMSGERR_INVALIDSTARTLINE,
    EMSGERR_INVALIDREQLINE,
    EMSGERR_INVALIDSTATUSLINE,
    EMSGERR_INVALIDMETHOD,
    EMSGERR_INVALIDLANTAG,
    EMSGERR_INVALIDVERSION,
    EMSGERR_INVALIDSTATUSCODE,
    EMSGERR_INVALIDRSNPHRS,
    EMSGERR_INVALIDURI,
    EMSGERR_INVALIDABSURI,
    EMSGERR_INVALIDSCHEME,
    EMSGERR_INVALIDUSER,
    EMSGERR_INVALIDPSWD,
    EMSGERR_INVALIDHOST,
    EMSGERR_INVALIDPORT,
    EMSGERR_INVALIDURL,
    EMSGERR_INVALIDNAME,
    EMSGERR_INVALIDVALUE,
    EMSGERR_INVALIDADDRSPEC,
    EMSGERR_INVALIDSEQ,
    EMSGERR_INVALIDMTYPE,
    EMSGERR_INVALIDMSUBTYPE,
    EMSGERR_INVALIDHDR,
    EMSGERR_INVALIDACCEPTHDR,
    EMSGERR_INVALIDACCEPTENCODINGHDR,
    EMSGERR_INVALIDRESOURCEPRIORITYHDR,
    EMSGERR_INVALIDACPTRCSPRIORITYHDR,
    EMSGERR_INVALIDCALLIDHDR,
    EMSGERR_INVALIDCSEQHDR,
    EMSGERR_INVALIDCONTENTLENHDR,
    EMSGERR_INVALIDMAXFDHDR,
    EMSGERR_INVALIDVIAHDR,
    EMSGERR_INVALIDTOHDR,
    EMSGERR_INVALIDFROMHDR,
    EMSGERR_INVALIDHDRPARAM,
    EMSGERR_INVALIDDATEHDR,
    EMSGERR_INVALIDINFOHDR,
    EMSGERR_INVALIDVIAPROTOCOLNAME,
    EMSGERR_INVALIDVIAPROTOCOLVER,
    EMSGERR_INVALIDDISPLAYNAME,
    EMSGERR_INVALIDNUM,
    EMSGERR_INVALIDCSEQ,
    EMSGERR_INVALIDRETRYAFTER,
    EMSGERR_INVALIDMAXFD,
    EMSGERR_INVALIDEXPIRES,
    EMSGERR_INVALIDEMPRM,
    EMSGERR_INVALIDCOMMENT,
    EMSGERR_INVALIDCALLID,
    EMSGERR_INVALIDWARNCODE,
    EMSGERR_INVALIDDIGEST,
    EMSGERR_ENCODING,
    EMSGERR_INVALIDTOKEN,
    EMSGERR_INVALIDIDENTITY,
    EMSGERR_INVALIDUTFTEXT,
    EMSGERR_INVALIDLANGUAGERNG,
    EMSGERR_INVALIDMIMEBODY,
    EMSGERR_INVALIDSESSIONID,

    /*missing error*/
    EMSGERR_STARTLINEMISSING,
    EMSGERR_REQLINEMISSING,
    EMSGERR_STATUSLINEMISSING,
    EMSGERR_METHODMISSING,
    EMSGERR_STATUSCODEMISSING,
    EMSGERR_SIPVERSIONMISSING,
    EMSGERR_RSNPHRSMISSING,
    EMSGERR_REQURIMISSING,
    EMSGERR_SIPURIMISSING,
    EMSGERR_ABSURIMISSING,
    EMSGERR_NAMEMISSING,
    EMSGERR_USERMISSING,
    EMSGERR_PSWDMISSING,
    EMSGERR_HOSTMISSING,
    EMSGERR_PORTMISSING,
    EMSGERR_URLMISSING,
    EMSGERR_SIPHDRMISSING,
    EMSGERR_NAMEVALUELISTMISSING,
    EMSGERR_NAMEADDRMISSING,
    EMSGERR_HDRVALMISSING,
    /*Sip Message header missing errors
      Note: don't insert any enumration b/w it*/
    EMSGERR_HDRMISSINGSTART,
    EMSGERR_VIAMISSING,
    EMSGERR_FROMMISSING,
    EMSGERR_TOMISSING,
    EMSGERR_CALLIDMISSING,
    EMSGERR_CSEQMISSING,
    EMSGERR_MAXFORWARDSMISSING,
    EMSGERR_DATEMISSING,
    EMSGERR_CONTACTMISSING,
    EMSGERR_CONTENTTYPEMISSING,
    EMSGERR_CONTENTLENMISSING,
    /*regular headers*/
    EMSGERR_ACCEPTMISSING,
    EMSGERR_ACCEPTCONTACTMISSING,
    EMSGERR_ACCEPTENCODINGMISSING,
    EMSGERR_ACCEPTLANGUAGEMISSING,
    EMSGERR_ACCEPTRESOURCEPRIORITYMISSING,
    EMSGERR_ALERTINFOMISSING,
    EMSGERR_ALLOWMISSING,
    EMSGERR_ALLOWEVENTSMISSING,
    EMSGERR_ANSWERMODEMISSING,
    EMSGERR_AUTHENTICATIONINFOMISSING,
    EMSGERR_AUTHORIZATIONMISSING,
    EMSGERR_CALLINFOMISSING,
    /*Entity Releted Headers*/
    EMSGERR_CONTENTDISPOSITIONMISSING,
    EMSGERR_CONTENTENCODINGMISSING,
    EMSGERR_CONTENTLANGUAGEMISSING,
    /*General Headers*/
    EMSGERR_ENCRYPTIONMISSING,
    EMSGERR_ERRORINFOMISSING,
    EMSGERR_EVENTMISSING,
    EMSGERR_EXPIRESMISSING,
    EMSGERR_FLOWTIMERMISSING,
    EMSGERR_HIDEMISSING,
    EMSGERR_HISTORYINFOMISSING,
    EMSGERR_IDENTITYMISSING,
    EMSGERR_IDENTITYINFOMISSING,
    EMSGERR_INREPLYTOMISSING,
    EMSGERR_JOINMISSING,
    EMSGERR_MIMEVERSIONMISSING,
    EMSGERR_MINEXPIRESMISSING,
    EMSGERR_MINSEMISSING,
    EMSGERR_ORGANIZATIONMISSING,
    EMSGERR_PATHMISSING,
    EMSGERR_PERMISSIONMISSINGMISSING,
    EMSGERR_PRIORITYMISSING,
    EMSGERR_PRIVANSWERMODEMISSING,
    EMSGERR_PRIVACYMISSING,
    EMSGERR_PROXYAUTHENTICATEMISSING,
    EMSGERR_PROXYAUTHORIZATIONMISSING,
    EMSGERR_PROXYREQUIREMISSING,
    EMSGERR_RACKMISSING,
    EMSGERR_REASONMISSING,
    EMSGERR_RECORDROUTEMISSING,
    EMSGERR_REFERSUBMISSING,
    EMSGERR_REFERTOMISSING,
    EMSGERR_REFERREDBYMISSING,
    EMSGERR_REJECTCONTACTMISSING,
    EMSGERR_REPLACESMISSING,
    EMSGERR_REPLYTOMISSING,
    EMSGERR_REQUESTDISPOSITIONMISSING,
    EMSGERR_REQUIREMISSING,
    EMSGERR_RESOURCEPRIORITYMISSING,
    EMSGERR_RESPONSEKEYMISSING,
    EMSGERR_RETRYAFTERMISSING,
    EMSGERR_ROUTEMISSING,
    EMSGERR_RSEQMISSING,
    EMSGERR_SECURITYCLIENTMISSING,
    EMSGERR_SECURITYSERVERMISSING,
    EMSGERR_SECURITYVERIFYMISSING,
    EMSGERR_SERVERMISSING,
    EMSGERR_SERVICEROUTEMISSING,
    EMSGERR_SESSIONEXPIRESMISSING,
    EMSGERR_SIPETAGMISSING,
    EMSGERR_SIPIFMATCHMISSING,
    EMSGERR_SUBJECTMISSING,
    EMSGERR_SUPPORTEDMISSING,
    EMSGERR_SUBSCRIPTIONSTATEMISSING,
    EMSGERR_SUPPRESSIFMATCHMISSING,
    EMSGERR_TARGETDIALOGMISSING,
    EMSGERR_TIMESTAMPMISSING,
    EMSGERR_TRIGGERCONSENTMISSING,
    EMSGERR_UNSUPPORTEDMISSING,
    EMSGERR_USERAGENTMISSING,
    EMSGERR_WARNINGMISSING,
    EMSGERR_WWWAUTHENTICATEMISSING,
    /* Private Header List*/
    EMSGERR_PACCESSNETWORKINFOMISSING,
    EMSGERR_PANSWERSTATEMISSING,
    EMSGERR_PASSERTEDIDENTITYMISSING,
    EMSGERR_PASSOCIATEDURIMISSING,
    EMSGERR_PCALLEDPARTYIDMISSING,
    EMSGERR_PCHARGINGFUNCTIONADDRESSESMISSING,
    EMSGERR_PCHARGINGVECTORMISSING,
    EMSGERR_PDCSBILLINGINFOMISSING,
    EMSGERR_PDCSLAESMISSING,
    EMSGERR_PDCSOSPSMISSING,
    EMSGERR_PDCSREDIRECTMISSING,
    EMSGERR_PDCSTRACEPARTYIDMISSING,
    EMSGERR_PEARLYMEDIAMISSING,
    EMSGERR_PMEDIAAUTHORIZATIONMISSING,
    EMSGERR_PPREFERREDIDENTITYMISSING,
    EMSGERR_PPROFILEKEYMISSING,
    EMSGERR_PREFUSEDURIHDRLMISSING,
    EMSGERR_PSERVEDUSERMISSING,
    EMSGERR_PUSERDATABASEMISSING,
    EMSGERR_PVISITEDNETWORKIDMISSING,
    EMSGERR_HDRMISSINGEND,
    /*End of header missing*/
    /*Header Param missing Errors*/
    EMSGERR_ADDRSPECMISSING,
    EMSGERR_PROTOCOLNAMEMISSING,
    EMSGERR_PROTOCOLVERSIONMISSING,
    EMSGERR_TRANSPORTMISSING,
    EMSGERR_PARAMMISSING,
    EMSGERR_WARNCODEMISSING,
    EMSGERR_WARNAGENTMISSING,
    EMSGERR_WARNTEXTMISSING,
    EMSGERR_PACCESSTYPEMISSING,
    EMSGERR_PANSWERTYPEMISSING,

    ETXN_ERROREND,
    ETXN_INVALID = -1
} SipEn_ErrorTypes;

#endif  //__SIP_ERROR_H__
