/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.imsstack.imsservice.mmtel.sms;

import android.util.Base64;

import com.android.imsstack.enabler.mts.MtsController;
import com.android.imsstack.imsservice.mmtel.ImsCallContext;
import com.android.internal.annotations.VisibleForTesting;
import com.android.telephony.Rlog;

import java.io.ByteArrayOutputStream;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Provides the functionality of SMS Relay Layer as per 3GPP TS 24.011
 **/
public class SmsRelayLayer {
    private static final String TAG = "[GII-SmsRL] ";
    private final ImsCallContext mCallContext;
    private SmsTransferLayer mSmsTL = null;
    private MtsController mMtsController = null;
    private final MtsControllerListenerProxy mMtsControllerListener =
            new MtsControllerListenerProxy();
    private final Object mLock = new Object();
    //token-RPMessageReference synchronisation
    private AtomicInteger mRPMR = new AtomicInteger();
    private AtomicInteger mToken = new AtomicInteger();
    public Map<Integer, Integer> mMoMRTokenMap = new ConcurrentHashMap<>();
    public Map<Integer, Integer> mMTTokenMRMap = new ConcurrentHashMap<>();
    private static final boolean VDBG = true;
    /**
     * Listener to handle the events sent from SmsRelayLayer
     */
    public interface Listener {
        /**
         * notifies Transfer Layer when RP-Data is received
         * @param token unique token generated to trigger callbacks for this message
         * @param smsFormat the format of the message
         * @param messageType the message type of RPDU
         * @param pdu TPdu representing the contents of the message
         *
         * @return the result of handling Data at transfer layer
         */
        int notifyRLDataIndication(int token, int smsFormat,
                                             int messageType, byte[] pdu);

        /**
         * notifies Transfer Layer when RP-Ack/RP-Error is received
         * @param token provided in {@link #sendRPMessage(int, int, String, String, byte[])}
         * @param result result of sending the SMS.
         * @param reason reason in case status is failure.
         */
        void notifyRLReportIndication(int token, int result, int reason);
    }

    public SmsRelayLayer(ImsCallContext callContext) {
        mCallContext = callContext;
        mMtsController = new MtsController(mCallContext);
        if (mMtsController != null) {
            mMtsController.setListener(mMtsControllerListener);
        }
        mMtsController.startNativeConnection();
    }

    @VisibleForTesting
    public SmsRelayLayer(ImsCallContext callContext, MtsController mtsController) {
        mCallContext = callContext;
        if (mtsController == null) {
            mMtsController = new MtsController(mCallContext);
        } else {
            mMtsController = mtsController;
        }

        if (mMtsController != null) {
            mMtsController.setListener(mMtsControllerListener);
        }
        mMtsController.startNativeConnection();
    }

    private SmsRelayLayer.Listener mListener = null;

    public void setListener(SmsRelayLayer.Listener listener) {
        mListener = listener;
    }

    /**
     * Creates RPDU and requests MtsController to send RPDU to native
     * @param token unique token generated by platform used for
     *              callbacks for this specific message
     * @param rpType the Message Type with respect to RPDU
     * @param smsc the Short Message Service Center address.
     * @param destinationAddress the Target Address of the message
     * @param tpdu PDU representing the contents of the message.
     *
     * @return the result of sending RPDU to SMS Enabler
     */
    public int sendRPMessage(
            int token, int rpType, String smsc, String destinationAddress, byte[] tpdu) {
        try {
            Rlog.d(TAG, "sendRPMessage");
            byte[] encodedPdu = null;
            //TODO: To be fixed as per Bug Id: b/232048441
            if (rpType == SmsUtils.RP_DATA) {
                if (smsc == null || smsc.length() == 0) {
                    Rlog.i(TAG, "SmscAddress is null");
                    return SmsUtils.SMS_RESULT_INVALID_SMSC_ADDRESS;
                }
            }

            /**
             * DestinationAddress is null in case of RP-Ack.
             *  So assigning SMSC address to destination address
             */
            if (destinationAddress == null || destinationAddress.length() == 0) {
                destinationAddress = smsc;
            }

            int rpMR = -1;
            synchronized (mLock) {
                if (rpType == SmsUtils.RP_DATA) {
                    rpMR = getRPMessageReference();
                    mMoMRTokenMap.put(rpMR, token);
                } else if (rpType == SmsUtils.RP_ACK) {
                    if (mMTTokenMRMap.containsKey(token)) {
                        rpMR = mMTTokenMRMap.get(token);
                        mMTTokenMRMap.remove(token);
                    } else {
                        Rlog.i(TAG, "No Corresponding Rp-Data for the RP-Ack");
                        return SmsUtils.SMSRL_RESULT_TOKEN_DOES_NOT_EXIST;
                    }
                } else if (rpType == SmsUtils.RP_ERROR) {
                    if (mMTTokenMRMap.containsKey(token)) {
                        rpMR = mMTTokenMRMap.get(token);
                        mMTTokenMRMap.remove(token);
                    } else {
                        Rlog.i(TAG, "No Corresponding Rp-Data for the RP-Error");
                        return SmsUtils.SMSRL_RESULT_TOKEN_DOES_NOT_EXIST;
                    }
                } else if (rpType == SmsUtils.RP_SMMA) {
                    rpMR = getRPMessageReference();
                    mMoMRTokenMap.put(rpMR, token);
                } else {
                    Rlog.i(TAG, "Invalid message type");
                    return SmsUtils.SMSRL_RESULT_INVALID_RP_MESSAGE_TYPE;
                }
            }
            SmsRPdu pdu = new SmsRPdu(rpMR, rpType, smsc, 0, tpdu);
            encodedPdu = pdu.getRpduByteArray();
            if (encodedPdu == null) {
                Rlog.i(TAG, "Encoding Failed");
                return SmsUtils.SMSRL_RESULT_PDU_ENCODING_FAILED;
            }
            String pdu64 = Base64.encodeToString(encodedPdu, Base64.DEFAULT);
            boolean result = mMtsController.sendMessage(
                            SmsUtils.FORMAT_INT_3GPP,
                            pdu64,
                            smsc,
                            rpMR);
            if (!result) {
                Rlog.i(TAG, "failed to send Sms");
                return SmsUtils.SMSRL_RESULT_MTS_CONTROLLER_FAILED;
            }
            return SmsUtils.RESULT_SUCCESS;
        } catch (RuntimeException e) {
            Rlog.e(TAG, "Can not send sms: " + e.getMessage());
            return SmsUtils.SMSRL_RESULT_EXCEPTION;
        }
    }

    private int getRPMessageReference() {
        return (mRPMR.incrementAndGet() % SmsUtils.MAX_RPMR_VALUE);
    }

    class MtsControllerListenerProxy extends MtsController.Listener {
        @Override
        public void notifyStatusForOutgoingMessage(
                int reason, int format, int retryAfter, int messageReference) {
            try {
                Rlog.i(TAG, "notifyStatusForOutgoingMessage");
                //TODO: Will be Implemented in upcoming Error Handling CL
            } catch (RuntimeException e) {
                Rlog.e(TAG, "notifyStatusForOutgoingMessage Failed: " + e.getMessage());
            }
        }

        @Override
        public int notifyIncomingMessage(int smsFormat, String encodedData) {
            try {
                Rlog.d(TAG, "notifyIncomingMessage: smsFormat = " + smsFormat);
                int token = 0;
                int result;
                Listener listener = mListener;
                if (listener == null) {
                    Rlog.e("TAG", "Listener is null");
                    return mMtsController.MT_FAILURE;
                }
                encodedData = encodedData.replaceAll("\\s", "");
                byte[] pduData = Base64.decode(encodedData, Base64.NO_PADDING);
                if (VDBG) {
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < pduData.length; i++) {
                        sb.append(String.format("%02X ", pduData[i]));
                    }
                    Rlog.i(TAG, "RPDU = " + sb.toString());
                }
                if (smsFormat == SmsUtils.FORMAT_INT_3GPP2) {
                    token = mToken.incrementAndGet();
                    synchronized (mLock) {
                        Rlog.i("TAG", "calling notifyRLDataIndication with token = " + token);
                        result = listener.notifyRLDataIndication(token, smsFormat,
                                                                 SmsUtils.RP_DATA, pduData);
                    }
                    if (result != SmsUtils.RESULT_SUCCESS) {
                        return MtsController.MT_FAILURE;
                    }
                    return MtsController.MT_SUCCESS;
                }
                byte[] tpdu = null;
                SmsRPdu mtData = new SmsRPdu(pduData);
                Rlog.i(TAG, "rpdu fields: message type ="
                                + mtData.getMessageType()
                                + " messageRef ="
                                + mtData.getMessageRef()
                                + " Originating Address = "
                                + mtData.getOrigAddr());
                int messageRef = mtData.getMessageRef();
                if (mtData.getMessageType() == SmsUtils.RP_ACK) {
                    synchronized (mLock) {
                        if (mMoMRTokenMap.containsKey(messageRef)) {
                            token = mMoMRTokenMap.get(messageRef);
                            mMoMRTokenMap.remove(messageRef);
                            listener.notifyRLReportIndication(token, 1, 0);
                        } else {
                            Rlog.i(TAG, "No Matching RP-Data for Rp-Ack");
                            return mMtsController.MT_FAILURE;
                        }
                    }
                } else if (mtData.getMessageType() == SmsUtils.RP_DATA) {
                    tpdu = mtData.getUserData();
                    token = mToken.incrementAndGet();
                    /** Framework's TPdu Parser expects the TPdu be prepended with SC-Address.
                      * else the parser will throw exception. So prepending TPdu with
                      * RP-OriginatingAdrress.
                      */
                    ByteArrayOutputStream bo = new ByteArrayOutputStream(tpdu.length);
                    int originAddressLength  = pduData[SmsUtils.RPDU_ORIGIN_ADDR_LENGTH_INDEX];
                    bo.write(originAddressLength);
                    bo.write(pduData, SmsUtils.RPDU_ORIGIN_ADDR_VALUE_INDEX, originAddressLength);
                    bo.write(tpdu, 0, tpdu.length);
                    byte[] frameworkPdu = bo.toByteArray();
                    synchronized (mLock) {
                        mMTTokenMRMap.put(token, messageRef);
                        result = listener.notifyRLDataIndication(
                            token, smsFormat, SmsUtils.RP_DATA, frameworkPdu);
                        if (result != SmsUtils.RESULT_SUCCESS) {
                            return mMtsController.MT_FAILURE;
                        }
                    }
                }
                //TODO: Implementation Pending for RP-ERROR
                return mMtsController.MT_SUCCESS;
            } catch (RuntimeException e) {
                Rlog.e(TAG, "notifyIncomingMessage Failed " + e.getMessage());
                return mMtsController.MT_FAILURE;
            }
        }
    }
}
