/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef CREDENTIAL_H_
#define CREDENTIAL_H_

#include "ByteArray.h"

// Extensions for IMS AKA authentication
class ImsAkaParam
{
public:
    enum
    {
        RESULT_OK = 0,
        RESULT_NOK_SQN_SYNC_FAILED,
        RESULT_NOK_MAC_INVALID
    };

    // Status of ISIM authentication
    IMS_SINT32 m_nStatus;
    // Authentication token
    //  : A 112 bit value generated by the client upon experiencing an SQN synchronization failure
    AString m_strAuts;

    inline ImsAkaParam() :
            m_nStatus(RESULT_OK),
            m_strAuts(AString::ConstNull())
    {
    }

    inline ImsAkaParam(IN const ImsAkaParam& other) :
            m_nStatus(other.m_nStatus),
            m_strAuts(other.m_strAuts)
    {
    }

    inline ImsAkaParam& operator=(IN const ImsAkaParam& other)
    {
        if (this != &other)
        {
            m_nStatus = other.m_nStatus;
            m_strAuts = other.m_strAuts;
        }

        return (*this);
    }
};

class ImsSaKey
{
public:
    inline ImsSaKey() :
            m_objIk(ByteArray::ConstNull()),
            m_objCk(ByteArray::ConstNull())
    {
    }

    inline ImsSaKey(IN const ImsSaKey& other) :
            m_objIk(other.m_objIk),
            m_objCk(other.m_objCk)
    {
    }

    inline ImsSaKey& operator=(IN const ImsSaKey& other)
    {
        if (this != &other)
        {
            m_objIk = other.m_objIk;
            m_objCk = other.m_objCk;
        }

        return (*this);
    }

    inline const ByteArray& GetCk() const { return m_objCk; }

    inline const ByteArray& GetIk() const { return m_objIk; }

    inline void SetCk(IN const ByteArray& objCk) { m_objCk = objCk; }

    inline void SetIk(IN const ByteArray& objIk) { m_objIk = objIk; }

private:
    // Integrity key
    ByteArray m_objIk;
    // Encryption Key
    ByteArray m_objCk;
};

class Credential
{
public:
    Credential();
    Credential(IN const AString& strUsername, IN const AString& strPassword,
            IN const AString& strRealm);
    Credential(IN const Credential& other);
    inline ~Credential() {}

public:
    Credential& operator=(IN const Credential& other);

public:
    inline IMS_BOOL IsSameRealm(IN const AString& strRealm) const
    {
        return m_strRealm.Equals(strRealm);
    }
    inline const AString& GetPassword() const { return m_strPassword; }
    inline const AString& GetRealm() const { return m_strRealm; }
    inline const AString& GetUsername() const { return m_strUsername; }
    void SetCredentials(IN const AString& strUsername, IN const AString& strPassword,
            IN const AString& strRealm);
    inline void SetPassword(IN const AString& strPassword) { m_strPassword = strPassword; }
    inline void SetRealm(IN const AString& strRealm) { m_strRealm = strRealm; }
    inline void SetUsername(IN const AString& strUsername) { m_strUsername = strUsername; }

    // Extensions for IMS AKA authentication
    inline const ImsAkaParam& GetAkaResponse() const { return m_objAkaParam; }
    inline IMS_SINT32 GetType() const { return m_nTypeOfMd5; }
    void SetAkaResponse(IN IMS_SINT32 nStatus, IN const ByteArray& objRes,
            IN const ByteArray& objAuts = ByteArray::ConstNull());
    void SetAkaResponse(IN IMS_SINT32 nStatus, IN const ByteArray& objRes,
            IN const ByteArray& objIk, IN const ByteArray& objCk,
            IN const ByteArray& objAuts = ByteArray::ConstNull());
    inline void SetType(IN IMS_SINT32 nType) { m_nTypeOfMd5 = nType; }

    inline static const Credential& ConstNull() { return s_objSharedNull; }
    static ByteArray DeriveCkForAkav2(IN const ByteArray& objCk);
    static ByteArray DeriveIkForAkav2(IN const ByteArray& objIk);
    static IMS_SINT32 TranslateAlgorithm(IN const AString& strAlgorithm);

public:
    /// Type of algorithm which the device supports
    enum
    {
        /// Default algorithm
        TYPE_MD5 = 0,
        /// Digest AKAv1; If ISIM is supported, this value will be used
        TYPE_AKAv1_MD5,
        /// Digest AKAv2; If ISIM is supported, this value will be used
        TYPE_AKAv2_MD5
    };

    static const IMS_CHAR STR_MD5[];
    static const IMS_CHAR STR_AKAv1_MD5[];

    // Digest AKAv2
    static const IMS_CHAR STR_AKAv2_MD5[];
    static const IMS_UINT32 DIGEST_KEY_CK;
    static const IMS_UINT32 DIGEST_KEY_IK;
    static const IMS_UINT32 DIGEST_KEY_PASSWORD;
    static const IMS_UCHAR STR_DIGEST_KEY_CK[];
    static const IMS_UCHAR STR_DIGEST_KEY_IK[];
    static const IMS_UCHAR STR_DIGEST_KEY_PASSWORD[];

private:
    // AKAv1-MD5 / AKAv2-MD5 extensions
    enum
    {
        MAX_AUTH_RESP = 128
    };
    enum
    {
        MAX_AUTS = 64
    };

    IMS_SINT32 m_nTypeOfMd5;

    AString m_strUsername;
    AString m_strPassword;
    AString m_strRealm;

    // Extensions for IMS AKA authentication
    ImsAkaParam m_objAkaParam;

    static Credential s_objSharedNull;
};

#endif
