/*
    Author
    <table>
    date      author                    description
    --------  --------------            ----------
    20090302  toastops@                 Created
    </table>

    Description

*/

#ifndef _CREDENTIAL_H_
#define _CREDENTIAL_H_

#include "ByteArray.h"

// Extensions for IMS AKA authentication
class IMS_AKA
{
public:
    enum
    {
        RESULT_OK = 0,
        RESULT_NOK_SQN_SYNC_FAILED,
        RESULT_NOK_MAC_INVALID
    };

    // Status of ISIM authentication
    IMS_SINT32 nStatus;
    // Authentication token
    //  : A 112 bit value generated by the client upon experiencing an SQN synchronization failure
    AString strAUTS;

    inline IMS_AKA() :
            nStatus(RESULT_OK),
            strAUTS(AString::ConstNull())
    {
    }

    inline IMS_AKA(IN CONST IMS_AKA& objRHS) :
            nStatus(objRHS.nStatus),
            strAUTS(objRHS.strAUTS)
    {
    }

    inline IMS_AKA& operator=(IN CONST IMS_AKA& objRHS)
    {
        if (this != &objRHS)
        {
            nStatus = objRHS.nStatus;
            strAUTS = objRHS.strAUTS;
        }

        return (*this);
    }
};

class IMS_SA_KEY
{
public:
    inline IMS_SA_KEY() :
            objIK(ByteArray::ConstNull()),
            objCK(ByteArray::ConstNull())
    {
    }

    inline IMS_SA_KEY(IN CONST IMS_SA_KEY& objRHS) :
            objIK(objRHS.objIK),
            objCK(objRHS.objCK)
    {
    }

    inline IMS_SA_KEY& operator=(IN CONST IMS_SA_KEY& objRHS)
    {
        if (this != &objRHS)
        {
            objIK = objRHS.objIK;
            objCK = objRHS.objCK;
        }

        return (*this);
    }

    inline const ByteArray& GetCK() const { return objCK; }

    inline const ByteArray& GetIK() const { return objIK; }

    inline void SetCK(IN CONST ByteArray& objCK) { this->objCK = objCK; }

    inline void SetIK(IN CONST ByteArray& objIK) { this->objIK = objIK; }

private:
    // Integrity key
    ByteArray objIK;
    // Encryption Key
    ByteArray objCK;
};

class Credential
{
public:
    Credential();
    Credential(IN CONST AString& strUsername_, IN CONST AString& strPassword_,
            IN CONST AString& strRealm_);
    Credential(IN CONST Credential& objRHS);
    ~Credential();

public:
    Credential& operator=(IN CONST Credential& objRHS);

public:
    IMS_BOOL IsSameRealm(IN CONST AString& strRealm) const;
    const AString& GetPassword() const;
    const AString& GetRealm() const;
    const AString& GetUsername() const;
    void SetCredentials(IN CONST AString& strUsername, IN CONST AString& strPassword,
            IN CONST AString& strRealm);
    void SetPassword(IN CONST AString& strPassword);
    void SetRealm(IN CONST AString& strRealm);
    void SetUsername(IN CONST AString& strUsername);

    // Extensions for IMS AKA authentication
    const IMS_AKA& GetAKAResponse() const;
    IMS_SINT32 GetType() const;
    void SetAKAResponse(IN IMS_SINT32 nStatus, IN CONST ByteArray& objRES,
            IN CONST ByteArray& objAUTS = ByteArray::ConstNull());
    void SetAKAResponse(IN IMS_SINT32 nStatus, IN CONST ByteArray& objRES,
            IN CONST ByteArray& objIK, IN CONST ByteArray& objCK,
            IN CONST ByteArray& objAUTS = ByteArray::ConstNull());
    void SetType(IN IMS_SINT32 nType);

    inline static const Credential& ConstNull() { return s_objSharedNull; }
    static ByteArray DeriveCKForAKAv2(IN CONST ByteArray& objCK);
    static ByteArray DeriveIKForAKAv2(IN CONST ByteArray& objIK);
    static IMS_SINT32 TranslateAlgorithm(IN CONST AString& strAlgorithm);

public:
    // Type of algorithm which the device supports
    enum
    {
        // Default algorithm
        TYPE_MD5 = 0,
        // Digest AKAv1; If ISIM is supported, this value will be used
        TYPE_AKAv1_MD5,
        // Digest AKAv2; If ISIM is supported, this value will be used
        TYPE_AKAv2_MD5
    };

    static const IMS_CHAR STR_MD5[];
    static const IMS_CHAR STR_AKAv1_MD5[];

    // Digest AKAv2
    static const IMS_CHAR STR_AKAv2_MD5[];
    static const IMS_UINT32 DIGEST_KEY_CK;
    static const IMS_UINT32 DIGEST_KEY_IK;
    static const IMS_UINT32 DIGEST_KEY_PASSWORD;
    static const IMS_UCHAR STR_DIGEST_KEY_CK[];
    static const IMS_UCHAR STR_DIGEST_KEY_IK[];
    static const IMS_UCHAR STR_DIGEST_KEY_PASSWORD[];

private:
    // AKAv1-MD5 / AKAv2-MD5 extensions
    enum
    {
        MAX_AUTH_RESP = 128
    };
    enum
    {
        MAX_AUTS = 64
    };

    IMS_SINT32 nTypeOfMD5;

    AString strUsername;
    AString strPassword;
    AString strRealm;

    // Extensions for IMS AKA authentication
    IMS_AKA stAKAParam;

    static Credential s_objSharedNull;
};

#endif  // _CREDENTIAL_H_
