/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CONFIG_DEF_H_
#define CONFIG_DEF_H_

enum class Feature
{
    UNKNOWN = -1,
    REQUEST_URI_TYPE = 0,
    SUPPORT_GEOLOCATION_PIDF_IN_SIP_INVITE,
    SUPPORT_SIP_SESSION_ID_HEADER,
    INCLUDE_CALLER_ID_SERVICE_CODES_IN_SIP_INVITE,
    MULTIENDPOINT_SUPPORTED,
    SESSION_TIMER_SUPPORTED,
    SESSION_PRIVACY_TYPE,
    PRACK_SUPPORTED_FOR_18X,
    CONFERENCE_SUBSCRIBE_TYPE,
    VOICE_QOS_PRECONDITION_SUPPORTED,
    VOICE_ON_DEFAULT_BEARER_SUPPORTED,
    DEDICATED_BEARER_WAIT_TIMER,
    SRVCC_TYPE,
    RINGING_TIMER,
    RINGBACK_TIMER,
    CONFERENCE_FACTORY_URI,
    OIP_SOURCE_FROM_HEADER,
    MO_CALL_REQUEST_TIMEOUT,
    AUDIO_INACTIVITY_CALL_END_REASON,
    TIMER_18X,
    SUPPORT_CONFERENCE_REFER_SUBSCRIBE,
    ENABLE_CONFERENCE_SUBSCRIBE_BY_PARTICIPANT,
    CONFERENCE_SIP_FLOW_ORDER,
    CONFERENCE_INVITING_REFER_TYPE,
    POLICY_QOS_PRECONDITION_MECHANISM_WHILE_CALL_MODIFICATION,
    INCOMING_CALL_REJECT_CODE_FOR_USER_DECLINE,
    INCOMING_CALL_REJECT_CODE_FOR_NO_ANSWER,
    PRACK_UPDATE_RESPONSE_WAIT_TIMER,
    SESSION_REFRESH_TRIGGER_INTERVAL,
    REGISTRATION_RESTORATION_MODE_ON_504_FOR_INVITE,
    POLICY_ON_AUDIO_QOS_DEACTIVATION,
    ENABLE_SEND_REINVITE_ON_RAT_CHANGE,
    POLICY_FOR_MEDIA_TYPE_RESTRICTION_ON_CELLULAR,
    POLICY_FOR_MEDIA_TYPE_RESTRICTION_ON_CELLULAR_IN_ROAMING,
    POLICY_OF_LOCAL_NUMBERS,
    DEFAULT_EPS_BEARER_CONTEXT_USAGE_RESTRICTION_ON_CELLULAR,
    SILENT_REDIAL_INTERVAL,
    CALL_TYPE_AFTER_AUDIO_AND_VIDEO_CALL_MERGED,
    SHORT_CALL_CODE,
    ALLOW_MULTIPLE_CALL_INCLUDING_VIDEO_CALL,
    REJECT_CODE_FOR_CSFB,
    SILENT_REDIAL_MAX_RETRY_COUNT,
    POLICY_FOR_403_RESPONSE_FOR_INVITE,
    POLICY_FOR_CHECKING_QOS_WHILE_CALL_UPGRADING,
    REJECT_OFFERLESS_INVITE,
    CALL_MAX_COUNT,
    CALL_TERMINATE_REASON_HEADER,
    CALL_REJECT_REASON_PHRASE,

    // VT CONFIGURATIONS
    VIDEO_ON_DEFAULT_BEARER_SUPPORTED,
    VIDEO_QOS_PRECONDITION_SUPPORTED,
    CONVERT_REMOTE_RESPONSE_TIMER,
    CONVERT_USER_RESPONSE_TIMER,
    POLICY_ON_VIDEO_QOS_DEACTIVATION,
    SUPPORT_EARLY_SESSION,
    POLICY_FOR_TEXT_WITH_VIDEO,
    MINIMUM_BATTERY_LEVEL_FOR_LIMIT_VIDEO_CALL,

    // RTT CONFIGURATIONS
    TEXT_ON_DEFAULT_BEARER_SUPPORTED,
    TEXT_QOS_PRECONDITION_SUPPORTED,
    POLICY_ON_TEXT_QOS_DEACTIVATION,

    // WFC CONFIGURATIONS
    PIDF_SHORT_CODE,
    EMERGENCY_CALL_OVER_EMERGENCY_PDN,
    COUNTRY_CODE,

    // EMERGENCY CONFIGURATIONS
    RETRY_EMERGENCY_ON_IMS_PDN_BOOL,
    EMERGENCY_QOS_PRECONDITION_SUPPORTED,
    EMERGENCY_CALL_OVER_EMERGENCY_PDN_ON_CELLULAR,
    EMERGENCY_RETRY_WITHOUT_CHECKING380_CONTENT_FOR_NON_UE_DETECTABLE_EMERGENCY_CALL,
    EMERGENCY_T_CALL_TIMER,
    EMERGENCY_RINGBACK_TIMER,
    EMERGENCY_18X_TIMER,
    POLICY_FOR_EMERGENCY_URN_ESCV_MAPPING,

    // ASSET - SEPARATED?
    CHECK_CONFERENCE_EVENT_PACKAGE_VERSION,
    CONFERENCE_REFER_TO_URI_SOURCE_PAID,
    CONFERENCE_DROP_REFER_TO_URI_SOURCE_TYPE,
    ENABLE_FAKE_QOS_CALL_FLOW_ON_WIFI,
    MEDIA_TYPE_FOR_OFFERLESS_REINVITE,
    SUPPORT_VIDEO_CALL_UPGRADE_REGARDLESS_OF_FEATURE_TAGS,
    OIP_TYPE_FOR_UNAVAILABLE,
    ENABLE_OIP_HEADER_POLICY_FALLBACK,
    EMERGENCY_RTT_GUARD_TIMER,
    RETRY_EMERGENCY_CALL_OVER_EMERGENCY_PDN_WITH_NEXT_PCSCF,
    PRE_ALERTING_TIMER,
    POLICY_FOR_TCALL_TIMER_EXPIRY_OF_VOLTE_CALL,
    POLICY_FOR_TCALL_TIMER_EXPIRY_OF_VOLTE_EMERGENCY_CALL,
    POLICY_FOR_TCALL_TIMER_EXPIRY_OF_VOWIFI_CALL,
    CARRIER_SPECIFIC_SIP_HEADER,
    CHECK_AVCHANGE_FEATURE_FOR_CALL_CONVERTING_CAPABILITY,
    SUPPORT_REGISTRATION_RECOVERY_FOR_FAILURE_OF_SESSION_REFRESH,
    CALL_MAINTAINING_ON_REGISTRATION_SUSPENDED,
    REQUIRING_EMERGENCY_CALL_WHEN_VIDEO_EMERGENCY_CALL_FAILED,
    USE_MCID_SUPPLEMENTARY_SERVICE,
    USE_MMC_SUPPLEMENTARY_SERVICE,
    USE_LTE_PREFERRED_STATUS_FOR_SERVICE_CAPABILITY,
    ALLOW_INCOMING_HOLD_REQUEST_DURING_CONFERENCE_CALL,
    IGNORE_180_AFTER_183_RESPONSE,
    ADD_REPLACE_HEADER_FOR_CONFERENCE,
    VILTE_TO_VOLTE_RETRY_FAILURE_RESPONSE_CODE,
    USE_EMERGENCY_NUMBER_TRANSLATION_IN_ROAMING_STATUS,
    IGNORE_PRACK_DELIVERY_FAILURE,
    SUPPORT_VIDEO_CALL_ONLY_IN_VOPS_OFF_STATUS,
    BLOCK_WIFI_EMERGENCY_CALL_IF_NOT_PROVISIONED,
    REGISTRATION_DISCONNECT_REASON_TO_IGNORE,
    WIFI_EMERGENCY_18X_TIMER,
    SUPPORT_CANID_INFO,
    USE_CARRIER_SPECIFIC_CONTACT_HEADER_FOR_OPTIONS_RESPONSE,
    USE_CARRIER_SPECIFIC_REJECT_PHRASE_FOR_INCOMING_CALL_DURING_NO_REGISTRATION,
    ENABLE_REGISTRATION_RECOVERY_WHEN_CALL_REJECTED_BY_SERVER_ERROR,
    ENABLE_REGISTRATION_RECOVERY_WHEN_CALL_RETRY_UNAVAILABLE,
    REJECT_VOWIFI_VOICE_CALL_WHEN_VOWIFI_SETTING_OFF,
    CHECK_SERVER_OUTAGE_REASON_FOR_VXLTE_CALL,
    SET_VIDEO_TEXT_FEATURE_EXCLUSIVELY_IN_CONTACT_HEADER_BY_SESSION_TYPE,
    MAXIMUM_WAIT_TIMER_FOR_GEOLOCATION_PIDF_INFO,
    MAINTAIN_MULTIPLE_EARLY_SESSIONS_BY_FORKING,
    STOP_RINGBACK_TIMER_BY_183_WITH_SDP_BODY,
    INFORMATION_LEVEL_OF_GEOLOCATION_PIDF,
    MESSAGE_TYPE_SUPPORT_GEOLOCATION_PIDF,
    INITIALIZE_PEM_WHEN_NO_HEADER,
    POLICY_FOR_LOCAL_RINGBACK_TONE_WITH_180_RESPONSE,
    EPS_FALLBACK_WATCHDOG_TIME,
    SEND_UDP_KEEP_ALIVE_INTERVAL_TIME,
    CALL_REJECT_CODE_FOR_NOT_ACCEPTABLE_CALL_TYPE,
    RELEASE_EMERGENCY_PDN_WITH_EMERGENCY_CALL_FAIL,
    POLICY_FOR_ALERT_NOT_USING_PRECONDITION_MECHANISM,
    REQUIRED_CDMALESS_FEATURE_TAG,
    EMERGENCY_CALL_CURRENT_LOCATION_DISCOVERY_SUPPORTED,
    CHECK_UI_CONDITION_FOR_INCOMING_RESUME,
};

enum class TerminateType
{
    USER_ENDS_CALL = 0,
    RTP_TIMEOUT = 1,
    USER_ENDS_CALL_AND_RTP_TIMEOUT = 2,
    MEDIA_BEARER_LOSS = 3,
    SIP_TIMEOUT = 4,
    SIP_RESPONSE_TIMEOUT = 5,
    USER_ENDS_AND_SIP_RESPONSE_TIMEOUT = 6,
    CALL_SETUP_TIMEOUT = 7,
    TERMINATING_EARLY_DIALOG = 8,
    VOPS_OFF = 9,
    SESSION_REFRESH_FAILURE = 10,
    CONFERENCE_CALL_JOINED = 11,
};

enum class RejectType
{
    ON_CS_CALL = 0,
    ON_VI_LTE_AND_NO_LTE = 1,
    ON_CONNECTING_CALL = 2,
    EXCEEDS_MAX_CALL = 3,
    ON_CONVERTING = 4,
    NEGOTIATION_FAILURE = 5,
    NO_ANSWER_BY_USER = 6,
    VOWIFI_OFF = 7,
    USER_REJECT = 8,
};

enum class CarrierSpecificHeader
{
    AV_CHANGE = 0,
};

enum class MessageTypeForGeolocationPidf
{
    INVITE = 0,
    PROVISIONAL_RESPONSE = 1,
    FINAL_SUCCESS_RESPONSE = 2,
    FINAL_FAILURE_RESPONSE = 3,
};

#endif
