/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INTERFACE_MTS_MESSAGE_CONTROLLER_H_
#define INTERFACE_MTS_MESSAGE_CONTROLLER_H_

#include "MtsDef.h"

class IPageMessage;

class IMtsMessageController
{
public:
    virtual ~IMtsMessageController() {}

    /**
     * @brief Verifies if an MO SMS request is awaiting network response.
     *
     * @return IMS_TRUE if there is a pending MO SMS request, IMS_FALSE otherwise.
     */
    virtual IMS_BOOL HasPendingMoSms() const = 0;

    /**
     * @brief Processes an MO SMS request.
     *
     * @param eSmsFormat The format of the SMS.
     * @param pContent A pointer to the protocol data unit(PDU).
     * @param strAddress The address to send the SMS to.
     * @param nSeqId The unique token generated by the platform that should be used when triggering
     *               callbacks for this specific message.
     * @param bEmergency {@code IMS_TRUE} If the dialed number is an emergency number,
     *                   {@code IMS_FALSE} otherwise.
     * @param eServiceType The service type of the MO SMS message.
     * @param nRetryCount The SMS retry count, controlled by the upper layer.
     */
    virtual void ProcessMoSms(IN SmsFormatType eSmsFormat, IN ByteArray* pContent,
            IN const AString& strAddress, IN IMS_SINT32 nSeqId, IN IMS_BOOL bEmergency,
            IN MtsServiceType eServiceType, IN IMS_UINT32 nRetryCount) = 0;

    /**
     * @brief Processes an MT SMS request.
     *
     * @param piMessage A pointer to the IPageMessage object representing the MT SMS message.
     * @param eServiceType The service type of the MT SMS message.
     */
    virtual void ProcessMtSms(IN IPageMessage* piMessage, IN MtsServiceType eServiceType) = 0;

    /**
     * @brief Clears all SMS messages managed by the controller.
     */
    virtual void ClearAllMessages() = 0;
};

#endif
