/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INTERFACE_MTS_MESSAGE_H_
#define INTERFACE_MTS_MESSAGE_H_

#include "MtsDef.h"

class IPageMessage;

class IMtsMessage
{
public:
    virtual ~IMtsMessage(){};

    /**
     * @brief Gets the destination address of the message.
     *
     * @return The destination address.
     */
    virtual AString& GetDestination() = 0;

    /**
     * @brief Sets the destination address of the message.
     *
     * @param strDestination The destination address to set.
     */
    virtual void SetDestination(IN const AString& strDestination) = 0;

    /**
     * @brief Gets the IMPU of the message.
     *
     * @return The IMPU.
     */
    virtual AString& GetImpu() = 0;

    /**
     * @brief Sets the IMPU of the message.
     *
     * @param strImpu The IMPU to set.
     */
    virtual void SetImpu(IN const AString& strImpu) = 0;

    /**
     * @brief Gets the message reference of the message.
     *
     * @return The message reference.
     */
    virtual IMS_SINT32 GetMessageReference() = 0;

    /**
     * @brief Sets the message reference of the message.
     *
     * @param nMrOfRp The message reference to set.
     */
    virtual void SetMessageReference(IN IMS_SINT32 nMrOfRp) = 0;

    /**
     * @brief Gets the message type indicator (MTI) of the message.
     *
     * @return The message type indicator (MTI).
     */
    virtual IMS_SINT32 GetMti() = 0;

    /**
     * @brief Sets the message type indicator (MTI) of the message.
     *
     * @param nMti The message type indicator (MTI) to set.
     */
    virtual void SetMti(IN IMS_SINT32 nMti) = 0;

    /**
     * @brief Gets the IPageMessage object associated with the message.
     *
     * @return A pointer to the IPageMessage object.
     */
    virtual IPageMessage* GetPageMessage() const = 0;

    /**
     * @brief Sets the IPageMessage object associated with the message.
     *
     * @param piPageMessage A pointer to the IPageMessage object to set.
     */
    virtual void SetPageMessage(IN IPageMessage* piPageMessage) = 0;

    /**
     * @brief Gets the SMS retry count.
     *
     * @return The SMS retry count.
     */
    virtual IMS_UINT32 GetRetryCount() const = 0;

    /**
     * @brief Sets the SMS retry count.
     *
     * @param nRetryCount The SMS retry count.
     */
    virtual void SetRetryCount(IN IMS_UINT32 nRetryCount) = 0;

    /**
     * @brief Gets the unique token generated by the platform that should be used when triggering
     *        callbacks for this specific message.
     *
     * @return The sequence ID.
     */
    virtual IMS_SINT32 GetSeqId() = 0;

    /**
     * @brief Sets the unique token generated by the platform.
     *
     * @param nSeqId The sequence ID to set.
     */
    virtual void SetSeqId(IN IMS_SINT32 nSeqId) = 0;

    /**
     * @brief Gets the slot ID of the message.
     *
     * @return The slot ID.
     */
    virtual IMS_SINT32 GetSlotId() = 0;

    /**
     * @brief Sets the slot ID of the message.
     *
     * @param nSlotId The slot ID to set.
     */
    virtual void SetSlotId(IN IMS_SINT32 nSlotId) = 0;

    /**
     * @brief Gets the SMS format of the message.
     *
     * @return The SMS format.
     */
    virtual SmsFormatType GetSmsFormat() = 0;

    /**
     * @brief Sets the SMS format of the message.
     *
     * @param eSmsFormat The SMS format to set.
     */
    virtual void SetSmsFormat(IN SmsFormatType eSmsFormat) = 0;

    /**
     * @brief Gets the size of the protocol data unit (PDU).
     *
     * @return The size of the protocol data unit (PDU).
     */
    virtual IMS_SINT32 GetSmSize() = 0;

    /**
     * @brief Sets the size of the protocol data unit (PDU).
     *
     * @param nSmSize The size of the protocol data unit to set.
     */
    virtual void SetSmSize(IN IMS_SINT32 nSmSize) = 0;

    /**
     * @brief Gets the transaction type of the message.
     *
     * @return The transaction type.
     */
    virtual MtsTransactionType GetTransactionType() = 0;

    /**
     * @brief Sets the transaction type of the message.
     *
     * @param eTransactionType The transaction type to set.
     */
    virtual void SetTransactionType(IN MtsTransactionType eTransactionType) = 0;

    /**
     * @brief Prints the information of the message.
     */
    virtual void PrintInfo() = 0;
};

#endif
