#ifndef FAIL_REASON_H_
#define FAIL_REASON_H_

#include "AString.h"
#include "IMSTypeDef.h"

struct FailReason
{
public:
    FailReason(IN IMS_SINT32 _nReason, IN IMS_SINT32 _nExtra, IN AString _strExtra) :
            nReason(_nReason),
            nExtra(_nExtra),
            strExtra(_strExtra)
    {
    }

    FailReason(IN IMS_SINT32 _nReason, IN IMS_SINT32 _nExtra) :
            FailReason(_nReason, _nExtra, AString::ConstNull())
    {
    }

    FailReason(IN IMS_SINT32 _nReason) :
            FailReason(_nReason, -1)
    {
    }

    FailReason(IN const FailReason& objRhs) :
            nReason(objRhs.nReason),
            nExtra(objRhs.nExtra),
            strExtra(objRhs.strExtra)
    {
    }

    FailReason& operator=(const FailReason& objRhs)
    {
        if (this != &objRhs)
        {
            nReason = objRhs.nReason;
            nExtra = objRhs.nExtra;
            strExtra = objRhs.strExtra;
        }

        return *this;
    }

    IMS_SINT32 nReason;
    IMS_SINT32 nExtra;
    AString strExtra;
};

enum
{
    FAIL_REASON_NONE = -1,
    FAIL_REASON_UNKNOWN = 0,

    FAIL_REASON_SERVICE_UNAVAILABLE = 101,
    FAIL_REASON_SERVICE_NOTREGISTERED,
    FAIL_REASON_SERVICE_OUT,
    FAIL_REASON_SERVICE_NOTSUPPORTCALL,
    FAIL_REASON_SERVICE_POWEROFF,
    FAIL_REASON_SERVICE_LOWBATTERY,
    FAIL_REASON_SERVICE_INCSCALL,
    FAIL_REASON_SERVICE_INVTCALL,
    FAIL_REASON_SERVICE_INOTHERSCALL,
    FAIL_REASON_SERVICE_MAXCALL,

    FAIL_REASON_NETWORK_OUTOFCOVERAGE = 201,
    FAIL_REASON_NETWORK_NO_LTE_COVERAGE,
    FAIL_REASON_NETWORK_NO_WIFI_COVERAGE,
    FAIL_REASON_NETWORK_NO_VOLTE,
    FAIL_REASON_NETWORK_ROAMING,
    FAIL_REASON_NETWORK_IPCHANGE,
    FAIL_REASON_NETWORK_BARRING,
    FAIL_REASON_NETWORK_SSAC,

    FAIL_REASON_SESSION_SERVERERROR = 301,
    FAIL_REASON_SESSION_FORBIDDEN = 302,
    FAIL_REASON_SESSION_NOTFOUND = 303,
    FAIL_REASON_SESSION_NOTSUPPORTED = 304,
    FAIL_REASON_SESSION_TEMPUNAVAILABLE = 305,
    FAIL_REASON_SESSION_BADADDRESS = 306,
    FAIL_REASON_SESSION_BUSY = 307,
    FAIL_REASON_SESSION_IN_SETUP = 308,
    FAIL_REASON_SESSION_REJECTED = 309,
    FAIL_REASON_SESSION_CANCELED = 310,
    FAIL_REASON_SESSION_USERTERMINATE = 311,
    FAIL_REASON_SESSION_TERMINATED = 312,
    FAIL_REASON_SESSION_UPDATE_FAILED = 313,
    FAIL_REASON_SESSION_BADRESPONSE = 314,
    FAIL_REASON_SESSION_NOTACCEPTABLE = 315,
    FAIL_REASON_SESSION_NOTACCEPTABLEHERE = 316,
    FAIL_REASON_SESSION_TIMEOUT = 317,
    FAIL_REASON_SESSION_REFRESH_OUT = 318,
    FAIL_REASON_SESSION_NOTREACHABLE = 319,
    FAIL_REASON_SESSION_REDIRECTION = 320,
    FAIL_REASON_SESSION_EARLYDIALOG = 321,
    FAIL_REASON_SESSION_IN_UPDATE = 322,
    FAIL_REASON_SESSION_SRVCC = 323,
    FAIL_REASON_SESSION_PRECONDITION = 324,
    FAIL_REASON_SESSION_SETUPFAILED = 325,
    FAIL_REASON_SESSION_IN_REFER = 326,
    FAIL_REASON_SESSION_DESTROYED = 327,
    FAIL_REASON_SESSION_RES_TIMEOUT = 328,

    FAIL_REASON_SESSION_SERVER_AUTH = 401,
    FAIL_REASON_SESSION_SERVER_REQUEST_TERMINATED = 402,
    FAIL_REASON_SESSION_SERVER_INTERNAL_ERROR = 403,
    FAIL_REASON_SESSION_SERVER_SERVICE_UNAVAILABLE = 404,
    FAIL_REASON_SESSION_SERVER_DECLINE = 405,

    FAIL_REASON_SESSION_RETRY = 500,
    FAIL_REASON_SESSION_RETRY1X = 501,
    FAIL_REASON_SESSION_RETRYVOLTE = 502,
    FAIL_REASON_SESSION_RETRY_RAT = 503,
    FAIL_REASON_SESSION_RETRY_SILENT = 504,
    FAIL_REASON_SESSION_RETRY_E_1X = 505,
    FAIL_REASON_SESSION_RETRY_E_VOLTE = 506,
    FAIL_REASON_SESSION_RETRY_E_RAT = 507,
    FAIL_REASON_SESSION_RETRY_R_RAT = 508,
    FAIL_REASON_SESSION_RETRY1X_FORCE = 509,
    FAIL_REASON_SESSION_RETRY_MAX = 510,

    FAIL_REASON_SESSION_MULTIDEVICE_ACCEPTED = 551,
    FAIL_REASON_SESSION_MULTIDEVICE_REJECTED = 552,
    FAIL_REASON_SESSION_MULTIDEVICE_LIMITED = 553,
    FAIL_REASON_SESSION_MULTIDEVICE_PULLED = 554,

    FAIL_REASON_FORBIDDEN_BARRING = 561,
    FAIL_REASON_FORBIDDEN_NOPROFILE = 562,
    FAIL_REASON_FORBIDDEN_EXPIRATION = 563,
    FAIL_REASON_FORBIDDEN_NOSUBSCRIBER = 564,

    FAIL_REASON_ECT_REPLACED = 571,
    FAIL_REASON_ECT_COMPLETED = 572,

    FAIL_REASON_MEDIA_INITFAIL = 601,
    FAIL_REASON_MEDIA_CODEC,
    FAIL_REASON_MEDIA_LOWEST_BIT_RATE,
    FAIL_REASON_MEDIA_CHECK_RADIO_CONNECTION,
    FAIL_REASON_MEDIA_NEGOFAIL,
    FAIL_REASON_MEDIA_NOMATCH,
    FAIL_REASON_MEDIA_NODATA,
    FAIL_REASON_MEDIA_UNKNOWN,

    FAIL_REASON_CONF_JOINED = 701,
    FAIL_REASON_CONF_NOT_ACCEPTABLE,
    FAIL_REASON_CONF_BUSY,
    FAIL_REASON_CONF_NOT_ACCEPTABLE_HERE,
    FAIL_REASON_CONF_TIMEOUT,
    FAIL_REASON_CONF_INTERNAL_ERROR,
    FAIL_REASON_CONF_ALONE,
    FAIL_REASON_CONF_UNKNOWN,

    FAIL_REASON_TO_MO_PROGRESSING = 801,
    FAIL_REASON_TO_MO_STARTED,
    FAIL_REASON_TO_MO_UPDATE,
    FAIL_REASON_TO_MT_NOANSWER,
    FAIL_REASON_TO_MT_UPDATE,
    FAIL_REASON_TO_MT_PRACK,

    FAIL_REASON_MAX = 999,
};

// FAIL_REASON_SESSION_SETUPFAILED
enum
{
    CODE_SETUPFAILED_NONE = 0,
    CODE_SETUPFAILED_OPENFAIL = 1,
    CODE_SETUPFAILED_STARTFAIL = 3,
    CODE_SETUPFAILED_ACCEPTFAIL = 5,
    CODE_SETUPFAILED_BLOCK_1XRETRY = 6,
};

// FAIL_REASON_SESSION_RETRY1X
enum
{
    CODE_1XRETRY_NONE = 0,
    CODE_1XRETRY_NORMAL = 1,
    CODE_1XRETRY_SILENT_REDIAL = 2,
    CODE_1XRETRY_PRIORITY_SET = 3,
};

// FAIL_REASON_SESSION_RETRYVOLTE
enum
{
    CODE_VoLTERETRY_NORMAL = 0,
    CODE_VoLTERETRY_EMERGENCY = 1,
    CODE_VoLTERETRY_OFFLINE = 2,
};

enum
{
    CODE_EMERGENCYSERVICE_INVALID = -1,
    CODE_EMERGENCYSERVICE_GENERIC = 0,
    CODE_EMERGENCYSERVICE_AMBULANCE = 1,
    CODE_EMERGENCYSERVICE_ANIMAL_CONTROL = 2,
    CODE_EMERGENCYSERVICE_FIRE = 3,
    CODE_EMERGENCYSERVICE_GAS = 4,
    CODE_EMERGENCYSERVICE_MARINE = 5,
    CODE_EMERGENCYSERVICE_MOUNTAIN = 6,
    CODE_EMERGENCYSERVICE_PHYSICIAN = 7,
    CODE_EMERGENCYSERVICE_POISON = 8,
    CODE_EMERGENCYSERVICE_POLICE = 9,
    CODE_EMERGENCYSERVICE_COUNTRY_SPECIFIC = 10,
};

enum
{
    REJECT_REASON_INVALID = -1,
    REJECT_REASON_UNKNOWN = 0,

    REJECT_REASON_DECLINE_USER = 2100,
    REJECT_REASON_DECLINE_NOANSWER = 2101,
    REJECT_REASON_DECLINE_NOBATTERY = 2102,
    REJECT_REASON_DECLINE_NORMAL = 2103,
    REJECT_REASON_DECLINE_CW = 2104,
    REJECT_REASON_DECLINE_UPDATE = 2105,

    REJECT_REASON_SERVICE_UNAVAILABLE = 2110,
    REJECT_REASON_SERVICE_TTY = 2111,

    REJECT_REASON_BUSY_ISCSCALL = 2120,

    REJECT_REASON_BUSY_ISEMERGENCY = 2123,
    REJECT_REASON_BUSY_ISWIFICALL = 2124,
    REJECT_REASON_BUSY_ISOTHERSCALL = 2125,
    REJECT_REASON_BUSY_ESTABLISHING = 2126,
    REJECT_REASON_BUSY_ALERTING = 2127,
    REJECT_REASON_BUSY_MAXCALL = 2128,
    REJECT_REASON_BUSY_NORMAL = 2129,
    REJECT_REASON_BUSY_IGNORE = 2130,
    REJECT_REASON_BUSY_HIDE = 2131,

    REJECT_REASON_SESSION_NOTSUPPORT = 2140,
    REJECT_REASON_SESSION_NOTACCEPTABLE = 2141,
    REJECT_REASON_SESSION_NOTACCEPTABLEHERE = 2142,
    REJECT_REASON_SESSION_UPDATE = 2143,
    REJECT_REASON_SESSION_BAD = 2144,
    REJECT_REASON_SESSION_FAIL = 2145,
    REJECT_REASON_SESSION_FAIL_PRECONDITION = 2146,
    REJECT_REASON_SESSION_INVALID_REFERRER_IDENTITY = 2147,

    REJECT_REASON_MEDIA_INITFAIL = 2160,
    REJECT_REASON_MEDIA_CODEC = 2161,
    REJECT_REASON_MEDIA_LOWEST_BIT_RATE = 2162,
    REJECT_REASON_MEDIA_CHECK_RADIO_CONNECTION = 2163,
    REJECT_REASON_MEDIA_NEGOFAIL = 2164,
    REJECT_REASON_MEDIA_FORMFAIL = 2165,
    REJECT_REASON_MEDIA_NODATA = 2166,
    REJECT_REASON_MEDIA_FAIL = 2167,

    REJECT_REASON_CONF_JOINED = 2170,

    REJECT_REASON_TO_MO_PROGRESSING = 2181,
    REJECT_REASON_TO_MO_STARTED = 2182,
    REJECT_REASON_TO_MO_UPDATE = 2183,
    REJECT_REASON_TO_MT_NOANSWER = 2184,
    REJECT_REASON_TO_MT_UPDATE = 2185,
    REJECT_REASON_TO_MT_PRACK = 2186,
    REJECT_REASON_TO_MO_WAIT_TERMINATED = 2187,
    REJECT_REASON_TO_MT_WAIT_TERMINATED = 2188,
    REJECT_REASON_TO_CONV_WAIT_TERMINATED = 2189,

    REJECT_REASON_MAX = 2199,
};

#endif
