/**
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef AUDIO_DEF_H_
#define AUDIO_DEF_H_

// == ENUM VALUES ==========================================================
typedef enum
{
    AUDIO_CODEC_NONE = 0,
    AUDIO_CODEC_AMR,
    AUDIO_CODEC_AMRWB,
    AUDIO_CODEC_EVS,
    AUDIO_CODEC_G711_PCMU,
    AUDIO_CODEC_G711_PCMA,
    AUDIO_CODEC_EVS_NB,
    AUDIO_CODEC_EVS_WB,
    AUDIO_CODEC_EVS_SWB,
    AUDIO_CODEC_EVS_FB,
    AUDIO_CODEC_MAX,
    AUDIO_CODEC_NOT_USED = 99
} AUDIO_CODEC;

typedef enum
{
    AUDIO_CODEC_BITRATE_INVALID = -1,

    // AMR case
    AUDIO_CODEC_BITRATE_AMR_475 = 0,
    AUDIO_CODEC_BITRATE_AMR_515,
    AUDIO_CODEC_BITRATE_AMR_590,
    AUDIO_CODEC_BITRATE_AMR_670,
    AUDIO_CODEC_BITRATE_AMR_740,
    AUDIO_CODEC_BITRATE_AMR_795,
    AUDIO_CODEC_BITRATE_AMR_1020,
    AUDIO_CODEC_BITRATE_AMR_1220,

    // AMR WB case
    AUDIO_CODEC_BITRATE_AMR_WB_660 = 10,
    AUDIO_CODEC_BITRATE_AMR_WB_885,
    AUDIO_CODEC_BITRATE_AMR_WB_1265,
    AUDIO_CODEC_BITRATE_AMR_WB_1425,
    AUDIO_CODEC_BITRATE_AMR_WB_1585,
    AUDIO_CODEC_BITRATE_AMR_WB_1825,
    AUDIO_CODEC_BITRATE_AMR_WB_1985,
    AUDIO_CODEC_BITRATE_AMR_WB_2305,
    AUDIO_CODEC_BITRATE_AMR_WB_2385,

    // EVS Primary mode case
    AUDIO_CODEC_BITRATE_EVS_590 = 20,
    AUDIO_CODEC_BITRATE_EVS_720,
    AUDIO_CODEC_BITRATE_EVS_800,
    AUDIO_CODEC_BITRATE_EVS_960,
    AUDIO_CODEC_BITRATE_EVS_1320,
    AUDIO_CODEC_BITRATE_EVS_1640,
    AUDIO_CODEC_BITRATE_EVS_2440,
    AUDIO_CODEC_BITRATE_EVS_3200,
    AUDIO_CODEC_BITRATE_EVS_4800,
    AUDIO_CODEC_BITRATE_EVS_6400,
    AUDIO_CODEC_BITRATE_EVS_9600,
    AUDIO_CODEC_BITRATE_EVS_12800,

    // EVS channel aware mode case
    AUDIO_CODEC_BITRATE_EVS_1320_CHA_2 = 35,
    AUDIO_CODEC_BITRATE_EVS_1320_CHA_3,
    AUDIO_CODEC_BITRATE_EVS_1320_CHA_5,
    AUDIO_CODEC_BITRATE_EVS_1320_CHA_7,

    // EVS AMR IO mode case
    AUDIO_CODEC_BITRATE_EVS_IO_660 = 40,
    AUDIO_CODEC_BITRATE_EVS_IO_885,
    AUDIO_CODEC_BITRATE_EVS_IO_1265,
    AUDIO_CODEC_BITRATE_EVS_IO_1425,
    AUDIO_CODEC_BITRATE_EVS_IO_1585,
    AUDIO_CODEC_BITRATE_EVS_IO_1825,
    AUDIO_CODEC_BITRATE_EVS_IO_1985,
    AUDIO_CODEC_BITRATE_EVS_IO_2305,
    AUDIO_CODEC_BITRATE_EVS_IO_2385,

    AUDIO_CODEC_BITRATE_MAX = 65535
} AUDIO_CODEC_BITRATE;

typedef enum
{
    AUDIO_CODEC_BANDWIDTH_INVALID = -1,
    AUDIO_CODEC_BANDWIDTH_NB = 0,
    AUDIO_CODEC_BANDWIDTH_WB = 1,
    AUDIO_CODEC_BANDWIDTH_SWB = 2,
    AUDIO_CODEC_BANDWIDTH_FB = 3,
} AUDIO_CODEC_BANDWIDTH;

typedef enum
{
    AUDIO_CODEC_QUALITY_INVALID = -1,

    AUDIO_CODEC_QUALITY_AMR = 0,
    AUDIO_CODEC_QUALITY_AMRWB = 1,
    AUDIO_CODEC_QUALITY_EVS = 2,
    AUDIO_CODEC_QUALITY_EVS_CHA = 3,
    AUDIO_CODEC_QUALITY_EVS_AMR_IO = 4,
    AUDIO_CODEC_QUALITY_G711 = 5,
} AUDIO_CODEC_QUALITY;

typedef enum
{
    /** EVS narrow band only */
    EVS_BW_NB = 1 << AUDIO_CODEC_BANDWIDTH_NB,
    /** EVS wide band only */
    EVS_BW_WB = 1 << AUDIO_CODEC_BANDWIDTH_WB,
    /** EVS super wide band only */
    EVS_BW_SWB = 1 << AUDIO_CODEC_BANDWIDTH_SWB,
    /** EVS full band only */
    EVS_BW_FB = 1 << AUDIO_CODEC_BANDWIDTH_FB,
} AUDIO_EVS_BANDWIDTH_BIT;

typedef enum
{
    IMS_EVS_CONFIG_INVALID = 0,
    IMS_EVS_CONFIG_A1,
    IMS_EVS_CONFIG_A2,
    IMS_EVS_CONFIG_B0,
    IMS_EVS_CONFIG_B1,
    IMS_EVS_CONFIG_B2,
} IMS_EVS_CONFIG;

#endif
