/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INTERFACE_MTS_JNI_H_
#define INTERFACE_MTS_JNI_H_

#include "INativeEnabler.h"
#include "MtsDef.h"

class AString;
class ByteArray;

class IMtsJni : public INativeEnabler
{
public:
    virtual ~IMtsJni() {};

    /**
     * @brief Sends a request for a mobile originated SMS, dispatching it based on Mts service type.
     *
     * This function initiates the process of sending a mobile originated (MO) SMS.
     * It determines the appropriate Mts service (e.g., normal or emergency) and
     * ensures the SMS is sent through the correct IMS network path.
     *
     * @param eSmsFormat The format of the SMS.
     * @param pContent A pointer to the protocol data unit (PDU).
     * @param strAddress The address to send the SMS to.
     * @param nSeqId The unique token generated by the platform that should be used when triggering
     *               callbacks for this specific message.
     * @param bEmergency {@code IMS_TRUE} If the dialed number is an emergency number,
     *                   {@code IMS_FALSE} otherwise.
     */
    virtual void SendMoSmsByServiceType(IN SmsFormatType eSmsFormat, IN ByteArray* pContent,
            IN const AString& strAddress, IN IMS_SINT32 nSeqId, IN IMS_BOOL bEmergency,
            IN IMS_UINT32 nRetryCount) = 0;
};

#endif
